RD-725 run tests on master
cloudify-cosmo/cloudify-stage pull request #1165
Opened 2021-01-05 12:52 UTC by yuvlar

2021-01-05 13:13 UTC, warolv requested changes

2021-01-05 13:13 UTC, warolv commented on jenkins/Jenkinsfile
> +        build(job: 'Stage-UI-System-Test')
@yuval, you need to send params there I think ? like branch name ...

2021-01-06 08:50 UTC, yuvlar commented on jenkins/Jenkinsfile
> +        build(job: 'Stage-UI-System-Test')
Fixed

2021-01-06 08:51 UTC, warolv approved these changes

2021-01-06 08:54 UTC, merged