Rd 1598 upload blueprints per selected technology in getting started
cloudify-cosmo/cloudify-stage pull request #1258
Opened 2021-03-22 13:48 UTC by gregcfy

This PR contains automatic blueprints upload feature for the selected by the user technologies in Getting Started Modal (developed in https://github.com/cloudify-cosmo/cloudify-stage/pull/1233).

The task for blueprints upload: https://cloudifysource.atlassian.net/browse/RD-1598

The main idea: Technologies have defined blueprints in json schema that will be installed automatically - user doesn't select blueprints by self. At the end of the installation, the user sees only blueprints upload summary as: `blueprint will be installed` or `blueprint is already installed`.

End of installation screenshot (only one UI visible change):

![image](https://user-images.githubusercontent.com/78533022/111999290-1fdfb880-8b1d-11eb-9e9e-c3b7aff42c25.png)

2021-03-23 07:48 UTC, Gelio commented
Hey, thanks for mentioning me :smile: I'm sorry, but I'm a bit stretched with Environments at the moment and I don't see myself having bandwidth for reviewing this PR :worried:

2021-03-25 10:01 UTC, kubama commented on app/translations/en.json
> +            "blueprintUploadError": "{{blueprint.blueprintName}} blueprint upload error:\n{{uploadError}}",
I think blueprint name should be used directly here, without the need for the wrapping object.

2021-04-02 14:41 UTC, gregcfy commented on app/components/GettingStartedModal/installation/process.ts
> +        async_upload: true,
if we do not use, backend throws timeout exception

2021-04-02 14:46 UTC, gregcfy commented on app/components/GettingStartedModal/GettingStartedModal.tsx
> +    // because of plugins and blueprints can be defined there
comments removed

2021-04-02 14:47 UTC, gregcfy commented on app/components/GettingStartedModal/blueprints/model.ts
> +};
now `Response` suffix is used.

2021-04-02 14:49 UTC, gregcfy commented on app/components/GettingStartedModal/blueprints/useFetchBlueprints.ts
> +const useFetchBlueprints = () => {
`useFetchBlueprints` now uses common fetch hook

2021-04-02 14:50 UTC, gregcfy commented on app/components/GettingStartedModal/installation/tasks.ts
> +    if (currentBlueprints && currentBlueprints.blueprints) {
fixed

2021-04-02 14:53 UTC, gregcfy commented on app/components/GettingStartedModal/installation/tasks.ts
> +                }
fixed

2021-04-02 14:54 UTC, gregcfy commented on app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
> +        <UnsafelyTypedForm style={{ minHeight: '150px' }} loading={tasksLoading}>
fixed

2021-04-02 14:55 UTC, gregcfy commented on app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
> +                        <p key={index}>{error}</p>
fixed

2021-04-02 14:55 UTC, gregcfy commented on app/translations/en.json
> +            "blueprintUploadError": "{{blueprint.blueprintName}} blueprint upload error:\n{{uploadError}}",
fixed

2021-04-02 15:48 UTC, kubama commented on app/components/GettingStartedModal/installation/process.ts
> +        async_upload: true,
If this is the case then this implementation could be still much smaller be reusing `BlueprintActions.waitUntilUploaded`

2021-04-02 15:50 UTC, kubama commented on app/components/GettingStartedModal/blueprints/model.ts
> +};
Please see `Stage.Types.PaginatedResponse` - it could be probably reused here

2021-04-02 16:23 UTC, kubama requested changes
I added some more comments, but I also have two general comments:
- even though review was re-requested not all comments from my previous review were addressed, I believe all skipped comments are still valid
- major issue: something is wrong with content of this PR - it contains unrelated changes, most noticeably changes to filters widget that are already in master; I suspect there might be more such changes - please check

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/installation/tasks.ts
> +    const usedBlueprints: Record<string, boolean> = {};
I would consider using `Set` here

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/model.ts
> +    mainBlueprint?: string;
This comment is still valid

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/managerHooks.ts
> +import { useMemo } from 'react';
Wasn't this file already merged?

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/schema.json
> +             "updatedAt": "2020-05-21T14:25:37Z"
I may be missing something, but looks like some of these properties are not used at all.

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/steps/SummaryStep/SecretsInstallationTasks.tsx
> +                        {i18n.t('gettingStartedModal.summary.secretCreateMessageSuffix', 'secret will be created')}
Unnecessary i18n default

2021-04-02 16:23 UTC, kubama commented on app/components/GettingStartedModal/steps/SummaryStep/SecretsInstallationTasks.tsx
> +                        {i18n.t('gettingStartedModal.summary.secretUpdateMessageSuffix', 'secret will be updated')}
Unnecessary i18n default

2021-04-02 16:23 UTC, kubama commented on app/translations/en.json
> +            "blueprintReadyMessageSuffix": "blueprint is already uploaded.",
This comment is still valid

2021-04-19 10:07 UTC, gregcfy commented on app/components/GettingStartedModal/installation/process.ts
> +        await manager.doPut(`/secrets/${encodeURIComponent(secret.name)}`, null, data);
maybe we should use it for security reasons?

2021-04-19 10:16 UTC, gregcfy commented on app/components/GettingStartedModal/installation/tasks.ts
> +    const usedBlueprints: Record<string, boolean> = {};
changed to `Set`

2021-04-19 10:24 UTC, kubama commented on app/components/GettingStartedModal/installation/process.ts
> +        await manager.doPut(`/secrets/${encodeURIComponent(secret.name)}`, null, data);
As I wrote, +1 for using it 🙂.

2021-04-19 10:41 UTC, gregcfy commented on app/components/GettingStartedModal/managerHooks.ts
> +import { useMemo } from 'react';
fixed, it was old file that is not needed

2021-04-19 11:08 UTC, gregcfy commented on app/components/GettingStartedModal/schema.json
> +             "updatedAt": "2020-05-21T14:25:37Z"
removed unused properties from schema

2021-04-19 11:10 UTC, gregcfy commented on app/components/GettingStartedModal/steps/SummaryStep/SecretsInstallationTasks.tsx
> +                        {i18n.t('gettingStartedModal.summary.secretCreateMessageSuffix', 'secret will be created')}
fixed

2021-04-19 11:11 UTC, gregcfy commented on app/components/GettingStartedModal/steps/SummaryStep/SecretsInstallationTasks.tsx
> +                        {i18n.t('gettingStartedModal.summary.secretUpdateMessageSuffix', 'secret will be updated')}
fixed

2021-04-19 11:35 UTC, gregcfy commented on app/components/GettingStartedModal/blueprints/model.ts
> +};
fixed

2021-04-19 13:55 UTC, gregcfy commented on app/components/GettingStartedModal/installation/process.ts
> +        async_upload: true,
After agreement TODO was created:
https://cloudifysource.atlassian.net/browse/RD-2086

2021-04-19 14:41 UTC, gregcfy commented on app/translations/en.json
> +            "blueprintReadyMessageSuffix": "blueprint is already uploaded.",
`blueprintReadyMessageSuffix` changed to `blueprintExistsMessageSuffix`, that communicate signals, it is not necessary to do installation to upload

2021-04-19 14:42 UTC, gregcfy commented on app/translations/en.json
> +            "blueprintsLoadingError": "Blueprints information loading error."
changed to `blueprintsMetadataLoadingError`

2021-04-19 15:02 UTC, gregcfy commented on app/components/GettingStartedModal/model.ts
> +    mainBlueprint?: string;
changed to:
```
export type GettingStartedSchemaBlueprint = {
    id: string;
    name: string;
    zipUrl: string;
    yamlFile?: string;
};
```

2021-04-20 06:03 UTC, kubama approved these changes
Thanks for addressing all the comments, I have no more comments so approving 👍.

2021-04-20 07:39 UTC, kubama submitted a review, later dismissed

2021-04-20 12:32 UTC, qooban reviewed
Added some comments. I didn't manage to get very deep in the review. And sorry, I don't have time today for UI tests.

2021-04-20 12:32 UTC, qooban commented on app/components/GettingStartedModal/localStorage.ts
> +    return true;
Have you executed system tests and all are passing?

FYI Please review Conclusions and Action Items from UI Weekly Meetings you did not attend during your vacation.

2021-04-20 12:32 UTC, qooban commented on app/components/GettingStartedModal/schema.json
>         "plugins": [
Do we have an issue in JIRA to:
1. move content of that file to the external source
2. have a configurable link to this JSON resource
?

I remember we were talking about it, but I can't find anything in RD-1440.

2021-04-20 12:32 UTC, qooban commented on app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
> +                    {pluginsInstallationTasks.error && <p>{pluginsInstallationTasks.error}</p>}
I'm wondering - maybe better would be to use `<List>` component from Semantic-UI to provide unordered list instead of separate paragraphs  (`<p>`) for each error group?

2021-04-20 12:32 UTC, qooban commented on app/translations/en.json
> +            "timeoutExceedError": "Timeout exceed.",
Probably more accurate would be:
```suggestion
            "timeoutExceededError": "Timeout exceeded.",
```

2021-04-20 12:32 UTC, qooban commented on app/components/GettingStartedModal/installation/process.ts
> +    const waitingTimeout = 5 * 60; // ~5 min = (N x 5s sleeps) + requests
What is `N` in the comment? Is it number of blueprints? What is `requests` in the comment? 

We've got constant value here (`5 * 60`), but explanation uses variables, so I'm a bit confused how it relates to each other 🙂

2021-04-20 12:32 UTC, qooban commented on .size-limit
> +        "limit": "324 KB",
Hmm... 10 kB from ~500 lines of code. Is it only from the new code?

2021-04-20 12:50 UTC, gregcfy commented on .size-limit
> +        "limit": "324 KB",
yes, only new feature

3.5KB comes from JSON configuration. As I remember in the previous PR ~3KB took generated code for 7 awaits + 7 asyncs - now we have 7-8 additional asyncs/awaits; all feature increased bundle size about 8.3KB.

2021-04-21 07:25 UTC, gregcfy commented on app/components/GettingStartedModal/schema.json
>         "plugins": [
Ticket created:
https://cloudifysource.atlassian.net/browse/RD-1440

2021-04-21 08:09 UTC, gregcfy commented on app/translations/en.json
> +            "timeoutExceedError": "Timeout exceed.",
fixed

2021-04-21 08:14 UTC, gregcfy commented on app/components/GettingStartedModal/installation/process.ts
> +    const waitingTimeout = 5 * 60; // ~5 min = (N x 5s sleeps) + requests
comment simplified

2021-04-21 09:02 UTC, gregcfy commented on app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
> +                    {pluginsInstallationTasks.error && <p>{pluginsInstallationTasks.error}</p>}
changed to `List`

2021-04-21 10:35 UTC, gregcfy commented on app/components/GettingStartedModal/localStorage.ts
> +    return true;
Getting started modal do not affect on the tests.
one not related test fails:
```
11:27:06  ────────────────────────────────────────────────────────────────────────────────────────────────────
11:27:06                                                                                                      
11:27:06    Running:  widgets/topology_spec.js                                                      (49 of 52)
11:30:58  
11:30:58    (Results)
11:30:58  
11:30:58    ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
11:30:58    │ Tests:        2                                                                                │
11:30:58    │ Passing:      1                                                                                │
11:30:58    │ Failing:      1                                                                                │
11:30:58    │ Pending:      0                                                                                │
11:30:58    │ Skipped:      0                                                                                │
11:30:58    │ Screenshots:  3                                                                                │
11:30:58    │ Video:        true                                                                             │
11:30:58    │ Duration:     3 minutes, 39 seconds                                                            │
11:30:58    │ Spec Ran:     widgets/topology_spec.js                                                         │
11:30:58    └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

2021-04-21 10:36 UTC, gregcfy commented on .size-limit
> +        "limit": "324 KB",
https://cloudifysource.atlassian.net/browse/RD-1440 will decrease bundle size a little

2021-04-21 13:03 UTC, qooban commented on app/components/GettingStartedModal/schema.json
>         "plugins": [
RD-1440? I assume you are talking about RD-2095?

Why is it outside of the Getting Started epic (RD-1440)?

2021-04-21 13:05 UTC, qooban commented on .size-limit
> +        "limit": "324 KB",
RD-1440? It's Getting Started epic.

2021-04-21 13:11 UTC, qooban reviewed
There are some open discussions and I'll be out of the office tomorrow. I think one approval is fine in case of this PR. So once @kubama approves it you can merge. Just be sure that all system tests are passing.

2021-04-21 14:09 UTC, gregcfy commented on .size-limit
> +        "limit": "324 KB",
https://cloudifysource.atlassian.net/browse/RD-2095 - copy paste mistake

2021-04-21 14:35 UTC, kubama commented on app/components/GettingStartedModal/installation/process.ts
> +    const stepSleep = 5; // 5 seconds
How about going further and adding the unit to the variable name?
```suggestion
    const waitingTimeoutSecs = 5 * 60;
    const stepSleepSecs = 5;
```

2021-04-22 06:02 UTC, gregcfy commented on app/components/GettingStartedModal/schema.json
>         "plugins": [
moved into Getting Started epic

2021-04-22 06:33 UTC, gregcfy commented on app/components/GettingStartedModal/installation/process.ts
> +    const stepSleep = 5; // 5 seconds
updated

2021-04-22 08:32 UTC, kubama approved these changes

2021-04-22 10:55 UTC, merged

2021-04-22 13:06 UTC, Gelio commented
Did anyone run system tests for this PR, or was it merged without any consideration of system tests :smile: ? I'm asking because I don't see any information about them here

2021-04-23 12:21 UTC, gregcfy commented
> Did anyone run system tests for this PR, or was it merged without any consideration of system tests  ? I'm asking because I don't see any information about them here

system tests passed except widgets/topology_spec.js that is related with different ticket
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/496/