RD-1846 - added permissions checking for who getting started modal is visible
cloudify-cosmo/cloudify-stage pull request #1283
Opened 2021-03-31 13:09 UTC by gregcfy

In this PR some condition that checks if the current user role has permissions to display getting started modal was added.
Task link: https://cloudifysource.atlassian.net/browse/RD-1846

This PR is related with: 
https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1107

2021-03-31 13:21 UTC, kubama submitted a review, later dismissed

2021-03-31 14:20 UTC, Gelio submitted a review, later dismissed
Looks good, although I have some non-blocking comments about the surrounding code :slightly_smiling_face:

2021-03-31 14:20 UTC, Gelio commented on app/components/GettingStartedModal/GettingStartedModal.tsx
>      const [modalOpen, setModalOpen] = useState(() => isGettingStartedModalDisabledInLocalStorage());
Optional, fun code golf:

```suggestion
    const [modalOpen, setModalOpen] = useState(isGettingStartedModalDisabledInLocalStorage);
```

2021-03-31 14:20 UTC, Gelio commented on app/components/GettingStartedModal/GettingStartedModal.tsx
>      const [modalOpen, setModalOpen] = useState(() => isGettingStartedModalDisabledInLocalStorage());
Digression:

This is how I read this line: initialize `modalOpen` to whether the modal is disabled in `localStorage`. Thus, it reads to me that when it is disabled in `localStorage`, `modalOpen = true`.

Could we change the naming to `modalClosed` or rename the function to `isGettingStartedModalEnabled`? This could be a separate ticket

2021-04-01 11:47 UTC, gregcfy commented on app/components/GettingStartedModal/GettingStartedModal.tsx
> +import { ReduxState } from '../../reducers';
updated

2021-04-01 11:49 UTC, gregcfy commented on app/components/GettingStartedModal/GettingStartedModal.tsx
>      const [modalOpen, setModalOpen] = useState(() => isGettingStartedModalDisabledInLocalStorage());
yeah, good point!

`localStorage['key']` returns `undefined` and `localStorage.getItem('key')` returns null for lack of key

fixed

2021-04-01 11:52 UTC, gregcfy commented on app/components/GettingStartedModal/GettingStartedModal.tsx
>      const [modalOpen, setModalOpen] = useState(() => isGettingStartedModalDisabledInLocalStorage());
ok, we can change it in separated PR

2021-04-01 12:21 UTC, kubama commented on app/components/GettingStartedModal/localStorage.ts
>      localStorage.setItem('getting-started-modal-disabled', 'true');
I'd suggest keeping function names shorter - given the context in which they are defined (file name) I think `InLocalStorage` suffix is not needed and actually redundant.

```suggestion
export const isGettingStartedModalDisabled = (): boolean =>
    localStorage.getItem('getting-started-modal-disabled') === 'true';

export const disableGettingStartedModal = (): void => {
    localStorage.setItem('getting-started-modal-disabled', 'true');
```

2021-04-01 13:09 UTC, gregcfy commented on app/components/GettingStartedModal/localStorage.ts
>      localStorage.setItem('getting-started-modal-disabled', 'true');
fixed

2021-04-01 14:27 UTC, kubama submitted a review, later dismissed

2021-04-02 08:16 UTC, Gelio submitted a review, later dismissed
Looks good, although there are merge conflicts :slightly_smiling_face:

2021-04-02 08:16 UTC, Gelio commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
Optional:

Extracting the key and reusing it in both function would ensure there are no typos :slightly_smiling_face:

2021-04-02 08:24 UTC, kubama commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
Actually, since the value is also a string (`'true'`) it could be extracted and reused as well, as it is prone to the same 'typo issue'.

2021-04-02 09:29 UTC, Gelio commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
Yeah :smile: We could alternatively use a different value, not just `true`, as seeing a boolean used as a string could be misleading :slightly_smiling_face: To me, any truthy value would work, so we could do

```suggestion
    !!localStorage.getItem('getting-started-modal-disabled');
```

2021-04-02 09:41 UTC, kubama commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
It is good, as 'yes' or '1' would work as well, for example if the value was set manually or in a different place, like a test.
It is bad, as 'no', 'false' or '0' would be considered a truthy value.
I think this is actually a common issue wherever string must be used to describe boolean value. Maybe there is something in npm that could solve it by recognizing common string values that can be used to express true or false?

2021-04-02 10:13 UTC, gregcfy commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
String(true) could be some solution too

2021-04-02 10:17 UTC, Gelio commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
Yeah :thinking: or using `JSON.stringify` on the value. Or, we could avoid a boolean value and use an enum https://understandlegacycode.com/blog/what-is-wrong-with-boolean-parameters/#3-if-it-makes-sense-use-an-enum

```ts
enum GettingStartedModalState {
  Disabled = 'disabled',
  Enabled = 'enabled',
}
```

(we could use `dismissed` instead of `disabled`), and use other key names, e.g. `getting-started-modal-dismissed-state`.

That's actually one of the ways to avoid booleans that is slightly more descriptive. 

I don't have a preference here, just putting it out there :slightly_smiling_face:

2021-04-02 16:42 UTC, kubama commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
@gregcfy So, what's your take on this? You re-requested the review but this thread is still open. The comments here are optional, but it would be nice to know if you are planning any actions or not 🙂.

2021-04-06 07:23 UTC, Gelio requested changes
Having it merged like that will cause the CI to fail again :slightly_smiling_face: This needs fixing :smile: 

btw. don't forget to run the system tests for this branch prior to merging :slightly_smiling_face:

2021-04-06 07:23 UTC, Gelio commented on app/components/GettingStartedModal/localStorage.ts
>      return false;
This should be changed to `true`, now that we are using the negation in `GettingStartedModal.tsx` to initialize the `modalOpen` state variable :slightly_smiling_face: Either we change it here, or we fix the tests to pass with the modal open :slightly_smiling_face:

2021-04-19 09:24 UTC, gregcfy commented on app/components/GettingStartedModal/localStorage.ts
> +    localStorage.getItem('getting-started-modal-disabled') === 'true';
I have decided to use JSON.stringify(true)

2021-04-19 09:24 UTC, gregcfy commented on app/components/GettingStartedModal/localStorage.ts
>      return false;
changed to `true`

2021-04-19 09:53 UTC, Gelio approved these changes

2021-04-19 10:05 UTC, merged