RD-1531Adjusting the layout for 6.0
cloudify-cosmo/cloudify-stage pull request #1377
Opened 2021-05-18 10:00 UTC by alexmolev

2021-05-18 11:09 UTC, Gelio reviewed
I have left some comments on the pluralization of names mostly. It works in the UI - I have checked all the added pages :slightly_smiling_face: 

btw. if we decide to change the names of the pages, it's worth it to also pluralize the files (e.g. `environment.json` -> `environments.json`)

2021-05-18 11:09 UTC, Gelio commented on templates/main-sys_admin.json
>    "pages": [
The `sys_admin` now has the same template as other users. Is this intended? :thinking:

2021-05-18 11:09 UTC, Gelio commented on templates/pages/environment.json
> +            "filterId": "csys-service-filter",
We probably want this to be

```suggestion
            "filterId": "csys-environment-filter",
```

2021-05-18 11:09 UTC, Gelio commented on templates/pages/service.json
> +  "name": "Deployment",
Do we want to name it _Deployment_ or perhaps

```suggestion
  "name": "Services",
```

e.g. there is "Local Blueprints" (plural)

2021-05-18 11:09 UTC, Gelio commented on templates/pages/resource.json
> +  "name": "Resource",
Existing page names are pluralized, e.g. Executions or Local Blueprints

```suggestion
  "name": "Resources",
```

2021-05-18 11:09 UTC, Gelio commented on templates/pages/environment.json
> +  "name": "Environment",
Existing page names are pluralized, e.g. Executions

```suggestion
  "name": "Environments",
```

2021-05-18 11:09 UTC, Gelio commented on templates/main-default.json
>    "pages": [
The `service.json` page is not used in those 2 templates. Is it intended?

2021-05-18 12:10 UTC, qooban commented on templates/main-default.json
> -    "logs"
Good point. As we are now resetting templates automatically on version change, there should be no problem if we remove not used pages. But maybe - to be fully safe - let's plan it for the next release (6.1)?

2021-05-18 12:12 UTC, alexmolev commented on templates/main-default.json
>    "pages": [
it is, please see line 9

2021-05-18 12:12 UTC, alexmolev commented on templates/main-default.json
> -    "logs"
I left them as I'm not sure if there are other places the link to them

2021-05-18 12:23 UTC, qooban reviewed
I did not test in the UI.

Added some comments. Mostly related to the file construction - missing or maybe not necessary fields. IMHO we should keep them as simple as possible, so e.g.:
1. if there is already default configuration available, let's not override it.
2. if it is possible to omit empty objects in `drillDownPages` or `configuration` fields, let's do it

2021-05-18 12:23 UTC, qooban commented on templates/main-sys_admin.json
>    "pages": [
Of course widgets with permissions for `sys_admin` only will not be visible for non-admins, but still - is it intended to have the same base for all type of user roles?

2021-05-18 12:23 UTC, qooban commented on templates/pages/environment.json
> +          }
I'm not sure - maybe we can remove it (empty `configuration` and `drillDownPages`) at all?
This comment is general for all places.

2021-05-18 12:23 UTC, qooban commented on templates/pages/resource.json
> +                ]
Probably not needed?

2021-05-18 12:23 UTC, qooban commented on templates/pages/resource.json
> +              "y": 0
`x` and `y` are always set to `0` in this file. I'm not sure how it'll behave. Probably the widgets should be displayed in the order how they are defined in the file, but what if not? 🙂 

In the other files AFAIR we defined the proper values for `x` and `y`.
Also, I'm wondering if it works without it defined.

2021-05-18 12:23 UTC, qooban commented on templates/pages/systemSetup.json
> +            },
Intentionally not defined `width` and `height`?

2021-05-18 12:59 UTC, Gelio commented on templates/main-default.json
> -    "logs"
I have created RD-2363 to take care of removing the unused pages in the future :slightly_smiling_face:

2021-05-18 13:01 UTC, Gelio commented
The comment about
> if we decide to change the names of the pages, it's worth it to also pluralize the files (e.g. environment.json -> environments.json)

still applies :slightly_smiling_face: 

Aside form that and addressing my previous comments, I don't have anything more to comment on here

2021-05-18 20:29 UTC, alexmolev commented on templates/main-sys_admin.json
>    "pages": [
I've removed systemSetup from none `sys_admin` users as they won't have permissions to it

2021-05-18 20:33 UTC, alexmolev commented on templates/pages/systemSetup.json
> +            },
yes

2021-05-19 07:07 UTC, Gelio approved these changes
Looks good to me :+1: I have only left 1 comment about file naming.

---

Can you make sure to run the system tests for this branch to make sure they won't break?

To do that, go to https://jenkins.cloudify.co/job/Stage-UI-System-Test/build?delay=0sec and change the `STAGE_BRANCH` to `RD-1531_env_dep_layout` (I could do that myself, but this way we share a bit of knowledge :smile:). Let me know if you'd prefer I start the tests

2021-05-19 07:07 UTC, Gelio commented on templates/pages/environment.json
> +{
Minor:

Can we have the files names pluralized? File names of the pages generally match the page name, and since the page name is pluralized (_Environments_ in this case), it makes sense to match the file name (`environments.json` in this case).

This applies to all new pages added in this PR (`environment.json`, `resource.json`, `service.json`)

2021-05-19 07:50 UTC, qooban requested changes
This time I spent much more time on the review and went over the configuration for all added widgets. I did also UI tests. 

In general I recommend the following changes:
* avoid defining `configuration` whenever it is not necessary
* use the same `height` for all widgets defined in Resources and System Setup pages (as they are in tabs and look'n'feel will be better when they share the same height)

I added code suggestions to make it easier to apply.

I also spotted a bug (not related): https://cloudifysource.atlassian.net/browse/RD-2371 (assigned it to myself, fix will be quick, already consulted Mateusz about it)

2021-05-19 07:50 UTC, qooban commented on templates/pages/environment.json
> +            "filterByParentDeployment": false
I still think we should avoid explicitly defining all the configuration details if they are the same as defaults.
Also, because you listed `fieldsToShow`, you missed recently added `id`, so it is another argument for not specifying anything that is not necessary.

My suggestion for this part is to have just:
```suggestion
            "filterId": "csys-environment-filter"
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/service.json
> +          },
I suggest to keep just:
```suggestion
          "configuration": {
            "filterId": "csys-service-filter"
          },
```
as all other configuration parameters are the same as default values.

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              },
As it is possible to filter logs by nodes and node instances, we should allow `filterByNodes` and `filterByNodeInstances`. Also, Events/Logs widget supports more than one resource, so `allowMultipleSelection` should be turned on.

```suggestion
              "configuration": {
                "pollingTime": 10,
                "filterByBlueprints": true,
                "filterByDeployments": true,
                "filterByExecutions": true,
                "filterByNodes": true,
                "filterByNodeInstances": true,
                "filterByExecutionsStatus": false,
                "filterBySiteName": false,
                "allowMultipleSelection": true
              },
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              }
All configuration parameters are the same as default values, so I suggest to remove it:

```suggestion
```

2021-05-19 07:50 UTC, qooban commented on templates/pages/systemSetup.json
> +              "height": 17,
I suggest to keep the `height` of all widgets in the page the same. It will look better IMHO when you switch between tabs.

https://user-images.githubusercontent.com/5202105/118775049-cc70b900-b886-11eb-9ae6-df52586c3fe5.mp4

2021-05-19 07:50 UTC, qooban commented on templates/pages/resource.json
> +              "height": 17,
I suggest to keep the `height` of all widgets in the page the same. It will look better IMHO when you switch between tabs.

https://user-images.githubusercontent.com/5202105/118775049-cc70b900-b886-11eb-9ae6-df52586c3fe5.mp4

2021-05-19 10:24 UTC, alexmolev commented on templates/pages/environment.json
> +          }
done

2021-05-19 10:25 UTC, alexmolev commented on templates/pages/resource.json
> +                ]
done

2021-05-19 10:25 UTC, alexmolev commented on templates/pages/resource.json
> +              "y": 0
done

2021-05-19 10:25 UTC, alexmolev commented on templates/pages/environment.json
> +{
done

2021-05-19 10:25 UTC, alexmolev commented on templates/pages/resource.json
> +              }
done

2021-05-19 10:25 UTC, alexmolev commented on templates/pages/resource.json
> +              }
done

2021-05-19 10:26 UTC, alexmolev commented on templates/pages/systemSetup.json
> +              "height": 17,
done

2021-05-19 10:26 UTC, alexmolev commented on templates/pages/resource.json
> +              }
done

2021-05-19 12:06 UTC, qooban commented
@alexmolev Let me know once you finish.
Also, have you checked how Tours behave with the new pages set?

We normally schedule manually full system tests execution for each PR, so you can schedule one here: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/ (just click "Run with Parameters" and use your branch as `STAGE_BRANCH`). It can help verify if such a change will not brake anything.

2021-05-19 14:42 UTC, Gelio approved these changes
Looks good to me, but I did not test the latest version in the UI :slightly_smiling_face:

2021-05-19 19:57 UTC, alexmolev commented
@qooban 
I'll need your help with it, wasn't able to make tour changes be applied on my local dev environment.
I think the best will be as discussed previously is to disable the tour feature. As some tour can't be fixed due to navigate between tabs limitation.

Please find below the status and let's discuss tomorrow

`Cloudify Console Overview` - works
`Cloudify Console Dashboard` - works
`Initial Manager Setup` - broken, `tenant_management` page doesn't exist anymore and was replaced with `System Setup` also previously widgets were one under another, currently they are spread between the tabs. tabs can't be navigated through URLs so it's a bit hard to make it working.
`From Blueprint to Execution` - Doesn't work. Can be fixed. The pages names were changed. The content for catalogue, blueprints remained. Services is the only page which has a different widget.
`Day two process` - Doesn't work, probably should be rewritten as it's entirely new widget

2021-05-20 07:32 UTC, qooban commented
FYI I'm starting the final review and Tours check.

2021-05-20 07:44 UTC, qooban commented on templates/pages/resources.json
> +              }
Is it necessary?

2021-05-20 07:44 UTC, qooban commented on templates/pages/resources.json
> +              }
Is it necessary?

2021-05-20 07:44 UTC, qooban commented on templates/pages/resources.json
> +              }
Is it necessary?

2021-05-20 07:47 UTC, qooban commented on templates/pages/environments.json
> +          "name": "Deployments view",
Optional:

I'm not sure, but maybe it should be:
```suggestion
          "name": "Environments",
```
?

2021-05-20 08:34 UTC, qooban commented
Tours update covered with https://github.com/cloudify-cosmo/cloudify-stage/pull/1384.

2021-05-20 09:54 UTC, alexmolev commented
Managed to run the Jenkins UI-Test
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/620/console

2021-05-20 09:55 UTC, alexmolev commented on templates/pages/resources.json
> +              }
not sure

2021-05-20 09:55 UTC, alexmolev commented on templates/pages/resources.json
> +              }
not sure

2021-05-20 09:55 UTC, alexmolev commented on templates/pages/resources.json
> +              }
not sure

2021-05-20 10:23 UTC, qooban commented on templates/pages/resources.json
> +              }
I checked it and removed (https://github.com/cloudify-cosmo/cloudify-stage/pull/1377/commits/3a640b8d08d4cc243739ceaac3964dc1d0782773).

2021-05-20 10:23 UTC, qooban commented on templates/pages/resources.json
> +              }
I checked it and removed (https://github.com/cloudify-cosmo/cloudify-stage/pull/1377/commits/3a640b8d08d4cc243739ceaac3964dc1d0782773).

2021-05-20 10:23 UTC, qooban commented on templates/pages/resources.json
> +              }
I checked it and removed (https://github.com/cloudify-cosmo/cloudify-stage/pull/1377/commits/3a640b8d08d4cc243739ceaac3964dc1d0782773).

2021-05-20 10:23 UTC, qooban commented on templates/pages/resources.json
> +              }
I checked it and removed (https://github.com/cloudify-cosmo/cloudify-stage/pull/1377/commits/3a640b8d08d4cc243739ceaac3964dc1d0782773).

2021-05-20 10:26 UTC, qooban commented
@alexmolev 

I have updated the PR with small changes in `resources.json`. JSON files changes looks good for me now. 

The only thing we should take care of are system tests. I see that you are facing CI issues, unfortunately.
So you can see what we are facing almost every day 🙂

2021-05-20 15:53 UTC, Gelio approved these changes

2021-05-21 09:30 UTC, qooban commented on test/cypress/integration/widgets/sites_map_spec.js
> -        cy.activate('valid_spire_license')
Spire license is not needed for Sites Map widget.

2021-05-21 09:31 UTC, qooban commented on test/cypress/integration/widgets/sites_spec.js
> -        cy.activate('valid_spire_license')
Spire license is not necessary to use Sites widget.

2021-05-21 09:48 UTC, qooban commented
I updated:
1. System tests (RD-2415)
2. Pages for Community version (RD-2418)

I think the PR is in the shape ready for final reviews and merge.

I'd like to have full system tests execution confirmation, but knowing how unstable it is, I wouldn't base on it, only.
Anyways, started: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/633/

2021-05-21 10:28 UTC, Gelio reviewed
I did not run the latest version in the UI and I did not go very deep into the JSON changes. Good job addressing all test failures :smile: I have left only some small comments/questions. I'll approve once those are addressed in come way :smile:

2021-05-21 10:28 UTC, Gelio commented on test/cypress/support/commands.ts
> +        if (pageName) cy.visitPage(pageName);
Do we need it here? IMO it does not add much value, as we can do

```ts
cy.visitPage('A').openTab('X');
```

instead of 

```ts
cy.openTab('X', 'A');
```

which IMO looks more readable :slightly_smiling_face:

2021-05-21 10:28 UTC, Gelio commented on test/cypress/integration/tours_spec.js
> +            checkTourSteps('Cloudify Console Dashboard', 5);
Shouldn't this be changed in the PR that modifies the tours? What's the reason of changing it here? :thinking:

2021-05-21 10:42 UTC, qooban commented on test/cypress/integration/tours_spec.js
> +            checkTourSteps('Cloudify Console Dashboard', 5);
Yes, it should be, but https://github.com/cloudify-cosmo/cloudify-stage/pull/1384 was already merged.

2021-05-21 10:43 UTC, qooban commented on test/cypress/support/commands.ts
> +        if (pageName) cy.visitPage(pageName);
Looks like a matter of preference. 
Anyways, changed.

2021-05-21 10:44 UTC, qooban commented
Updated `cy.openTab`. Checked both flow tests locally, passed.

2021-05-21 10:48 UTC, Gelio commented on test/cypress/integration/tours_spec.js
> +            checkTourSteps('Cloudify Console Dashboard', 5);
I see, ok :slightly_smiling_face:

2021-05-21 10:49 UTC, Gelio approved these changes

2021-05-21 11:56 UTC, qooban reviewed
I have to re-review it, so that my original "Request changes" gets cancelled 🙂 

P.S. I'll not self-approve it (I don't like my code ;-) )

2021-05-21 11:57 UTC, qooban approved these changes
OK, it seems I have to self-approve it ;-)

2021-05-21 11:58 UTC, merged