RD-1766 redesign ci workflow stage
cloudify-cosmo/cloudify-stage pull request #1445
Opened 2021-06-20 12:48 UTC by yuvlar

Suggested changes to Cloudify-stage in order to reduce the build runtime

2021-06-21 07:40 UTC, Gelio requested changes
This looks great :+1: 

I know you said that this improves the time by 5 minutes. Does it mean the job now runs in ~10 mins instead of ~15? That would be awesome :smile: 

I believe `.DS_Store` was committed by mistake, which is why I'm marking this as _request changes_ :slightly_smiling_face:

2021-06-21 07:40 UTC, Gelio commented on jenkins/Jenkinsfile
> +                dir("${STAGE_DIR}") {
Technically this is not 1-1 with https://cawemo.com/share/06df993a-57bc-4926-8741-d6b81025068f as building the RPM can start before `npm run beforebuild` is done :slightly_smiling_face: 

Is it what you agreed on with @qooban?

2021-06-21 07:40 UTC, Gelio commented on jenkins/Jenkinsfile
>          stage('Size') {
Shouldn't this be removed? We already have a size check in the `Run Builds & Build RPM` stage :slightly_smiling_face:

2021-06-21 07:40 UTC, Gelio commented on jenkins/Jenkinsfile
>              }
I can't comment in the `Docs` stage directly, but if I'm not mistaken, it can also be parallelized, so it can be moved to the `parallel` block in the `Run Builds & Build RPM` stage :slightly_smiling_face:

2021-06-21 08:26 UTC, yuvlar commented on jenkins/Jenkinsfile
>          stage('Size') {
npm run size does run in Build stage already, let me know if it can be removed

2021-06-21 08:27 UTC, yuvlar commented on jenkins/Jenkinsfile
>              }
Basically yes, but it has a command there to delete a folder that the tests use, so it crashes.
If it doesn't need to delete the folder that'll be great, let me know what you think

2021-06-21 08:28 UTC, yuvlar commented on jenkins/Jenkinsfile
> +                dir("${STAGE_DIR}") {
right, it wasn't possible to do it exactly like the diagram.
I could put the RPM stage before, but that would increase the build time

2021-06-21 08:31 UTC, yuvlar commented on jenkins/Jenkinsfile
>          stage('Size') {
nvm, my bad, I put it twice.
will be fixed

2021-06-22 06:31 UTC, Gelio requested changes
Looks definitely better, but I am wondering if we could squeeze even more parallelism :smile: 

Also, take a look at my previous review summary, because:

> I believe `.DS_Store` was committed by mistake, which is why I'm marking this as _request changes_

:slightly_smiling_face: 

We could also have a quick call to discuss the parallelism issues that I am not seeing :slightly_smiling_face:

2021-06-22 06:31 UTC, Gelio commented on jenkins/Jenkinsfile
> +                dir("${STAGE_DIR}") {
I see, no worries :slightly_smiling_face: We can leave it as-is if that's faster

I'm curious, though, as it would seem to me that running an independent step (building the RPM) earlier and in parallel would make the overall process finish sooner. Is it because there's not enough parallelization possible in the build system that it is overall slower? :thinking: 

I mean, just looking at the `Jenkinsfile` code I believe we could add more parallelism and try to do it just like the diagram, but I am not an expert in Jenkins :smile: I simply do not see the limitations that make the diagram impossible/hard to implement :thinking:

2021-06-22 06:31 UTC, Gelio commented on jenkins/Jenkinsfile
> +            branch "master"
Just FYI, we will have conflicts with #1446 :smile:

2021-06-22 06:31 UTC, Gelio commented on jenkins/Jenkinsfile
> +                sh 'npm run check-types'
Theoretically, these two can run in parallel :slightly_smiling_face: Not sure if that helps

2021-06-22 06:31 UTC, Gelio commented on jenkins/Jenkinsfile
> +    stage('Run Builds & Build RPM') {
This should probably say

```suggestion
    stage('Run tests') {
```

as the build step happens way earlier :slightly_smiling_face:

2021-06-22 06:31 UTC, Gelio commented on jenkins/Jenkinsfile
>              }
Interesting :smile: I believe it does not need to delete that `test` directory. Generally, if I'm not mistaken, it looks like some stages copy the whole project to a separate directory (e.g. `${workspace}/test`) and then run some commands there. Thus, the removal of the test directory is something that is only required by the build system.

We could even clean it up a bit and make each stage clean up after itself. The structure would then be like this, for example for docs:

```jenkinsfile
        stage('Docs'){
          steps {
            container('node'){
              sh "mkdir -p ${WORKSPACE}/docs && cp -rf ${WORKSPACE}/${stage_dir}/. ${WORKSPACE}/docs"
              dir("docs") {
                echo 'Generate widgets documentation'
                sh 'npm run docWidgets'

                echo 'Check if widgets documentation is up to date'
                sh 'git diff --exit-code ./widgets'

                echo 'Check if cloudify-ui-components version is the same as in official documentation'
                sh 'npm run docCheck'
              }
              sh 'rm -rf ${WORKSPACE}/docs'
            }
          }
        }
```

I believe this makes the stage:
1. Create a copy of the project to run the commands in isolation
2. Run the commands
3. Clean up

It would solve the problem of some stages trying to clean other stage's copies (e.g. `docs` trying to clean up `tests`) :slightly_smiling_face: 

Then, we could parallelize almost all the stages, just as in https://cawemo.com/share/06df993a-57bc-4926-8741-d6b81025068f

2021-06-23 09:29 UTC, Gelio approved these changes
LGTM! :smile: 

Just FYI, we will most likely need the same changes cherry-picked to 6.1.0-build :slightly_smiling_face:

2021-06-23 09:31 UTC, kubama commented
Seeing an in-depth review done by @Gelio I'll opt out of reviewing myself.

2021-06-23 10:33 UTC, warolv requested changes

2021-06-23 10:33 UTC, warolv commented on jenkins/Jenkinsfile
> +        stage('Prepare & run lint&check-types tests'){
Can you put more human-readable text?:-)

2021-06-23 10:33 UTC, warolv commented on jenkins/build-pod.yaml
> -        cpu: 1.5
not QOS anymore?

2021-06-23 11:40 UTC, Gelio commented on jenkins/Jenkinsfile
> +        stage('Prepare & run lint&check-types tests'){
An example could be `Install dependencies and execute basic checks`

2021-06-23 11:43 UTC, Gelio requested changes
The Jenkinsfile looks good. I have no clue about `build-pod` though. Also, please revert `.DS_Store` :smile: Aside from that, cool!

2021-06-23 12:08 UTC, yuvlar commented on jenkins/build-pod.yaml
> -        cpu: 1.5
It will be Burstable QoS, because in one parallel part, only the node container is used, and it should utilize the instance resources.
According to k8s, a higher cpu limit than the instance has won't evict the pod, but just might delay some processes.
I'll keep an eye on it anyway and if it'll cause issues I'll revert the limits to be like the requests

2021-06-23 12:08 UTC, yuvlar commented on jenkins/Jenkinsfile
> +        stage('Prepare & run lint&check-types tests'){
Will do and request a new review

2021-06-23 12:11 UTC, Gelio requested changes
I believe you may be missing [all](https://github.com/cloudify-cosmo/cloudify-stage/pull/1445#pullrequestreview-688113983) [my](https://github.com/cloudify-cosmo/cloudify-stage/pull/1445#pullrequestreview-689093770) [comments](https://github.com/cloudify-cosmo/cloudify-stage/pull/1445#pullrequestreview-690540991) about removing `.DS_Store` :slightly_smiling_face: Please remove it, we don't want it in the repo :smile:

2021-06-23 12:16 UTC, warolv approved these changes
Looks good!

2021-06-23 12:25 UTC, Gelio approved these changes
LGTM

2021-06-23 12:36 UTC, merged