RD-2341 Add deployment display name column to Events/Log widget.
cloudify-cosmo/cloudify-stage pull request #1482
Opened 2021-07-01 08:02 UTC by stepek

Adding deployment display name as `Deployment` and renaming currently `Deployment` column to `Deployment Id`.
![image](https://user-images.githubusercontent.com/5058678/124088645-6e252180-da53-11eb-9499-b9abcaeeebc1.png)

2021-07-01 08:28 UTC, kubama commented on widgets/events/src/EventsTable.tsx
> +                            _.size(data.executionId) !== 1 &&
Looks like some code duplication

2021-07-01 08:28 UTC, kubama commented on widgets/events/README.md
> +r# Events and Logs
A typo?

2021-07-01 08:28 UTC, kubama commented on widgets/events/src/widget.tsx
> +        }
This is something new to me... is there any place where deployment name is set in the context? I was aware of deployment ID, but not deployment display name.

2021-07-01 08:41 UTC, stepek commented on widgets/events/README.md
> +r# Events and Logs
yes :/

2021-07-01 08:44 UTC, stepek commented on widgets/events/src/widget.tsx
> +        }
I do this similar to deployment id, so this can be my mistake, let me remove this.

2021-07-01 08:46 UTC, stepek commented on widgets/events/src/EventsTable.tsx
> +                            _.size(data.executionId) !== 1 &&
there should be only 
```
 _.size(data.deploymentName) !== 1 &&
 _.size(data.nodeInstanceId) !== 1 &&
 _.size(data.executionId) !== 1 &&
```

2021-07-01 09:12 UTC, stepek commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment') >= 0
right, let me extract this to some function.

2021-07-01 10:17 UTC, Gelio reviewed
I appreciate having the screenshot in the PR description :+1:

2021-07-01 10:17 UTC, Gelio commented on widgets/events/README.md
> +   * Deployment Id
The process for changing the README is a bit more complex than just modifying it here :worried: We should be also modifying https://github.com/cloudify-cosmo/docs.getcloudify.org/blob/master/content/working_with/console/widgets/events.md and then running `npm run docWidgets` script to fetch the new README.

You can also see that the CI does not pass because the widgets' READMEs do not match the ones in the docs repository :slightly_frowning_face:

2021-07-01 10:17 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                        label="Deployment Id"
Can we use 

```suggestion
                        label="Deployment ID"
```

similar to https://github.com/cloudify-cosmo/cloudify-stage/blob/0df9298242f1de6cd7576066302a9f3c6adb7c5b/widgets/executions/src/widget.tsx#L33 ?

2021-07-01 10:19 UTC, stepek commented on widgets/events/src/EventsTable.tsx
> +                        label="Deployment Id"
this was named like other ID fields eg. `Node Id`

2021-07-01 10:19 UTC, stepek commented on widgets/events/README.md
> +   * Deployment Id
Thanks, will do

2021-07-01 10:40 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                        label="Deployment Id"
Hmm... ok, makes sense to have it consistent locally, but then it's inconsistent globally. I don't mind too much

2021-07-01 11:17 UTC, stepek commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment') >= 0
Moved to separate function

2021-07-01 11:44 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment') >= 0
I thought the reusable part was the 3 calls to `_.size`, not the `_.size(...) !== 1` :smile:

2021-07-01 12:25 UTC, kubama commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment') >= 0
Yes, it can be surely taken further. A function taking an array of values to check would fit well IMHO.

2021-07-02 05:12 UTC, stepek commented
### System tests 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/882/

2021-07-02 07:24 UTC, stepek commented
## system tests 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/883/

2021-07-05 07:02 UTC, Gelio commented on widgets/events/README.md
> +   * Deployment Id
Are you planning on modifying the readme :smile: ? I don't see any PRs in https://github.com/cloudify-cosmo/docs.getcloudify.org/pulls

2021-07-05 07:07 UTC, Gelio requested changes

2021-07-05 07:07 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                            !this.sOneElementLike(data.blueprintId) &&
Looks like a typo to me :smile: 

```suggestion
                            !this.isOneElementLike(data.blueprintId) &&
```

This applies to all calls for `isOneElementLike` :slightly_smiling_face:

2021-07-05 07:07 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +    isOneElementLike = (collection: object | string | null | undefined): boolean => {
Minor:

We could do

```suggestion
    isOneElementLike = (collection: unknown): boolean => {
```

to be more general :slightly_smiling_face:

2021-07-05 07:07 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment Id') >= 0
Shouldn't this be

```suggestion
                            fieldsToShow.indexOf('Deployment') >= 0
```

?

2021-07-05 07:07 UTC, Gelio commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment Id') >= 0
Minor:

Btw. we could also use `includes`, which IMO has a nicer API than `indexOf`

```suggestion
                            fieldsToShow.includes('Deployment Id')
```

This applies to all uses of `fieldsToShow.indexOf` in this file :slightly_smiling_face:

2021-07-12 06:36 UTC, stepek commented on widgets/events/src/EventsTable.tsx
> +                            fieldsToShow.indexOf('Deployment Id') >= 0
Will change, but i don't want to add more unnecessary changes in this PR.

2021-07-12 09:28 UTC, Gelio submitted a review, later dismissed
LGTM :+1: I did not run it in the UI myself :slightly_smiling_face: 

Let's make sure the e2e tests pass before we merge the PR

Also, do we want to cherry-pick this to 6.1? I'm not sure, it would be best if we asked @alexmolev

2021-07-13 06:31 UTC, stepek commented
## System tests
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/905/

regarding cherry pick to 6.1 got response from Alex and we want.

2021-07-13 08:55 UTC, Gelio approved these changes

2021-07-13 09:26 UTC, stepek commented
I changed base to 6.1 and rebased this to 6.1 because on master some of tests failing after removing jQuery url parsing.

2021-07-13 09:27 UTC, stepek commented
## New system test run 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/909/

2021-07-13 10:01 UTC, Gelio approved these changes

2021-07-13 11:27 UTC, merged