RD-2695 Remove jQuery usage from WidgetDynamicContent component.
cloudify-cosmo/cloudify-stage pull request #1491
Opened 2021-07-02 09:00 UTC by stepek

2021-07-12 09:55 UTC, Gelio reviewed
Nice jQuery simulation :+1: 

I added some comments about possible improvements :slightly_smiling_face: I'm not sure whether we want to maintain this `definition.events` feature :smile: Let's wait for the opinions from the rest of the team before we merge it :slightly_smiling_face: You can also postpone the code improvements until then, as maybe we will decide to remove this code altogether

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current === null) {
Will it ever be `null`? We initialize the ref with `{}`

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
>          if (widget.definition && widget.definition.events) {
Wow, this seems like a bizarre, outdated API that is not even public :smile: As I have grepped through the widgets code, I didn't find a single widget that uses `events` in its definition. I'm wondering if it's worth maintaining such an API.

Let's wait for @kubama's and @qooban's opinions on whether to keep it.

Personally, I would remove this `definition.events` behavior :smile:

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
>      attachEvents(container) {
Minor:

Can we add a type annotation here?

```suggestion
    attachEvents(container: HTMLDivElement | null) {
```

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current[`${event.selector}_${event}`]) {
Can we be a bit more explicit with the stringification of `event`?

```suggestion
                        if (this.attachedEvents.current[`${event.selector}_${JSON.strinfigy(event)}`]) {
```

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        this.attachedEvents = createRef<Record<string, any>>({});
Minor:

Do we need a ref? I believe we could just have a regular property here :slightly_smiling_face:

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current[`${event.selector}_${event}`]) {
We could avoid the stringification if instead of a single `Record<string, (event: Event) => void>` we had: ` Record<string, Record<object, (event: Event) => void>>` (first map for the selectors, second map for the event type -> listener mapping)

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                                .querySelector(event.selector)
Minor:

Can we extract this part to a separate variable so it can be reused (it's used in 2 places in this logic)? Like `const eventTarget`

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current[`${event.selector}_${event}`]) {
Minor:

Can we extract the condition to a separate variable to reuse it later (e.g. `const previousEventListener`)?

2021-07-12 09:55 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                                .removeEventListener(
Minor:

Can we add a bit more precise error handling? If `querySelector` won't find any elements, the error will be a very general `cannot invoke removeEventListener on undefined` and I believe we could make the error message a bit more developer-friendly :slightly_smiling_face: 

The same goes for `addEventListener` below :slightly_smiling_face: If we extract the result of `querySelector` to a variable (as I suggested in another comment), that check would only have to happen once :slightly_smiling_face:

2021-07-12 10:00 UTC, stepek commented on app/components/WidgetDynamicContent.tsx
>          if (widget.definition && widget.definition.events) {
This probably is old widget style related API

2021-07-14 08:34 UTC, stepek commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current === null) {
`createRef` don't have possibility to set initialized state
```
function createRef<T>(): RefObject<T>;
``` 

react has some small mishmash with class and hooks ref handling

2021-07-14 09:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        this.attachedEvents = createRef<Record<string, any>>({});
Another minor, if you decide to stick with `createRef` - from your comment in https://github.com/cloudify-cosmo/cloudify-stage/pull/1491#discussion_r669406841 it looks like `createRef` does not take any arguments :slightly_smiling_face: Thus, having `{}` is misleading

```suggestion
        this.attachedEvents = createRef<Record<string, any>>();
```

2021-07-14 09:26 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +                        if (this.attachedEvents.current === null) {
You are right :smile: Good point :+1: 

Did you consider initializing the ref with an empty object to avoid this `null` check? Or, we could just follow https://github.com/cloudify-cosmo/cloudify-stage/pull/1491/files/251be192fb3bedd45b2b66c7485b3c6f76e34af4#r667787378

2021-07-20 06:43 UTC, qooban reviewed
Added one comment. I think we can safely remove `definition.events` from the codebase.

2021-07-20 06:43 UTC, qooban commented on app/components/WidgetDynamicContent.tsx
>          if (widget.definition && widget.definition.events) {
Yes, this is very old API and there is very little chance that somebody is using it.
Searching through JIRA I found that we don't have it documented since v4.3 (ref.: https://cloudifysource.atlassian.net/browse/CYBL-195), so I think we can safely remove it from the code.

2021-07-20 10:42 UTC, qooban reviewed
I added one more sub-task to RD-258 to update documentation after all changes related to jQuery removal - RD-2775.

2021-07-20 10:42 UTC, qooban commented on app/components/WidgetDynamicContent.tsx
> -        }
I'm wondering if it is possible to keep it somehow without having jQuery?

As this method (`postRender`) is mentioned in our documentation (https://docs.cloudify.co/latest/developer/writing_widgets/widget-apis/), but similarly to `events` it is very unlikely that anybody uses it.

2021-07-20 10:44 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> -        }
I would also opt for keeping this API (it's also mentioned in our typings https://github.com/cloudify-cosmo/cloudify-stage/blob/efd8ecea5c7a9509d71f9d7ab1fb234af596312a/app/utils/StageAPI.ts#L163-L168)

2021-07-20 10:48 UTC, Gelio commented
Let's update the branch with `master` to get rid of the multibranch CI failure :smile:

2021-07-21 14:30 UTC, stepek commented on app/components/WidgetDynamicContent.tsx
> -        }
`componentDidUpdate` in this case can be better :) imho

2021-07-21 14:43 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> -        }
I just remembered - we will need it in `componentDidMount` too, if I'm not mistaken :smile:

2021-07-22 07:19 UTC, qooban commented on app/components/WidgetDynamicContent.tsx
> -        }
@stepek Please mention that during standup that it is going to be - after all - a breaking change.

2021-07-22 07:25 UTC, Gelio requested changes
To me, there is now a bug with how refs are used :smile: Thus, I'm blocking the review, just to be safe :slightly_smiling_face:

2021-07-22 07:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        this.containerRef = createRef<HTMLElement>();
Can you also declare this property in the class, so TypeScript sees it? I mean

```ts
private readonly containerRef: RefObject<HTMLElement>;
```

(not sure about the type, though, I did not check it in the editor)

2021-07-22 07:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        this.containerRef = createRef<HTMLElement>();
Can you also declare this property in the class, so TypeScript sees it? I mean

```ts
private readonly containerRef: RefObject<HTMLElement>;
```

(not sure about the type, though, I did not check it in the editor)

2021-07-22 07:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        if (widget.definition.postRender && this.containerRef) {
We should probably check if `this.containerRef.current` is defined, instead of `this.containerRef` (the ref object is always created in the constructor).

```suggestion
        if (widget.definition.postRender && this.containerRef.current) {
```

Also, can we have some console error if `this.containerRef.current` is not defined? This would mean there is a bug in the component :smile:

2021-07-22 07:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +            widget.definition.postRender(this.containerRef, widget, data.data, this.getToolbox());
We should probably be doing

```suggestion
            widget.definition.postRender(this.containerRef.current, widget, data.data, this.getToolbox());
```

2021-07-22 07:25 UTC, Gelio commented on app/components/WidgetDynamicContent.tsx
> +        if (widget.definition.postRender && this.containerRef) {
Do we not need this logic in `componentDidMount`?

2021-07-22 07:28 UTC, qooban reviewed
Looks better now. Added one comment.

2021-07-22 07:28 UTC, qooban commented on app/components/WidgetDynamicContent.tsx
> +            widget.definition.postRender(this.containerRef, widget, data.data, this.getToolbox());
Hmm... Shouldn't we pass `this.containerRef.current`?

2021-07-22 09:15 UTC, stepek commented on app/components/WidgetDynamicContent.tsx
> +            widget.definition.postRender(this.containerRef, widget, data.data, this.getToolbox());
sorry, right should be

2021-07-22 09:17 UTC, stepek commented
### System tests
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/945/

2021-07-22 11:21 UTC, stepek commented on app/components/WidgetDynamicContent.tsx
> +        this.containerRef = createRef<HTMLElement>();
sure, but i want to keep the same convention as other fields like `state`

2021-07-22 12:33 UTC, Gelio reviewed
Now it's just a matter of also calling the function in `componentDidMount` and this PR should be good to go :slightly_smiling_face:

2021-07-23 06:21 UTC, qooban reviewed
Agree with @Gelio last comment.

2021-07-23 08:16 UTC, stepek commented
@Gelio @qooban move to separate function and call it on `componentDidMount`

2021-07-23 08:48 UTC, Gelio approved these changes
LGTM :smile:

2021-07-23 11:31 UTC, stepek commented
###System test

https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/957/

2021-07-23 11:59 UTC, qooban approved these changes
Looks fine 👍🏻  Let's just wait for the confirmation from Mr Jenkins :-)

2021-07-23 12:26 UTC, Gelio commented
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/957/ is green, so we're finally ready to merge :smile:

2021-07-23 13:24 UTC, stepek commented
@Gelio @qooban Thanks !

2021-07-23 13:55 UTC, merged