RD-3979: Modified resourceLocation regexp
cloudify-cosmo/cloudify-stage pull request #1767
Opened 2022-01-21 10:39 UTC by NorbertAmartus

## Description

Changes consists of modifying resourceLocation regexp, so that it may cover the initial slash of the resource path.

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [x] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests

 

I've executed [System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1868)    
Currently in progress ... ⏲

## Documentation

N/A

2022-01-21 10:44 UTC, NorbertAmartus commented
@qooban what do you think, should I provide an additional test scenario?
Or it would be optional, as currently there was no tests related to generating `resourceLocation`?

2022-01-21 11:35 UTC, qooban approved these changes
> @qooban what do you think, should I provide an additional test scenario?
> Or it would be optional, as currently there were no tests related to generating resourceLocation?

Seems like `getResourceLocation` function would be good candidate for unit testing, but as it is not exported function, used only in one place I think we can treat adding test for this case as optional.

I'm good to go with merging this PR.

2022-01-21 11:35 UTC, qooban commented on widgets/blueprints/src/TerraformModal.tsx
> +            return resourceLocation.replace(/^[^/]*\//, '');
So basically right now all the starting characters except `/` + `/` will be removed from the `resourceLocation`, right?

I'm wondering what was the reason when the original solution was introduced.
We can check with @kubama I think.

2022-01-21 11:59 UTC, NorbertAmartus commented on widgets/blueprints/src/TerraformModal.tsx
> +            return resourceLocation.replace(/^[^/]*\//, '');
Yup, something like that   
I'd give a thumbs up for checking that, so that we'd be sure that an additionall `/` is not breaking any of the requirements, which we may not be aware of  😁

2022-01-21 12:18 UTC, NorbertAmartus commented
Some tests scenarios are failing, I'll investigate upon that matter

2022-01-24 10:24 UTC, kubama commented on widgets/blueprints/src/TerraformModal.tsx
> +            return resourceLocation.replace(/^[^/]*\//, '');
I don't think this is the right change. The `.` should stay for a scenario when there is no following subdirectory. I'm guessing it may be the reason behind system tests failure as there is a dedicated test for this case.

2022-01-24 10:26 UTC, kubama requested changes
Please see https://github.com/cloudify-cosmo/cloudify-stage/pull/1767/files#r790598831

2022-01-24 20:04 UTC, NorbertAmartus commented
I've created another branch, on which I've made some tests regarding fixing the discovered issues
I've good some promising results which resulted in the [completly green system tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1885/) 🎉 

Because of that I'll migrate those changes to this branch.
Changes consists of:
- increasing the number of retries inside the `waitForExecutionToEnd` function
- modifying regex so that the added `/` is being optional (in cases that we have trouble with -> in downloaded `zip` file there is only one terraform module, placed inside it's root directory), so that the resource location would equal to an empty string (which works the same as `./`, looking at my observation and Trammell suggestion), not the name of that single directory e.g. `single` (currently regexp was demending `/` at the end of the string, to be removed), which doesn't work 😁

2022-01-24 20:15 UTC, NorbertAmartus commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.waitForExecutionToEnd(deploymentId, 'install', { numberOfRetriesLeft: 120 });
The default number of retries is `60`, I've doubled it just to be sure that the tests are having enought time to be executed successfully (even on the local machines, not only on jenkins), which helped with one of the failing test scenarios 🎉

2022-01-25 07:42 UTC, qooban submitted a review, later dismissed
I'm OK with changes, but let's wait for final confirmation from Kuba M.

2022-01-25 08:41 UTC, kubama reviewed
Thanks for spending your time on in-depth investigation and testing.

I've got one more suggestion though. I would advice to add explicit test cases for `getResourceLocation` function that would document its behaviour (I think it could be refactored as a top-level function for easy independent testing). Without it I think it will be easily forgotten what's the purpose of the regexp.
I admit I should have added such test myself when this function was initially created 🙂.

2022-01-25 09:11 UTC, NorbertAmartus commented
> Thanks for spending your time on in-depth investigation and testing.
> 
> I've got one more suggestion though. I would advice to add explicit test cases for `getResourceLocation` function that would document its behaviour (I think it could be refactored as a top-level function for easy independent testing). Without it I think it will be easily forgotten what's the purpose of the regexp. I admit I should have added such test myself when this function was initially created 🙂.

Sure, it seems like a great idea!
To be honest, now I'm a little busy with updating the documentation, so I'd merge this PR (as there are no comments on the functionality), to meet the sprint requirements 😁    
In the near future, I'll create a PR which would contain an additional test scenario 😉 

@qooban, that would be okay?
(I've never tried that sort of actions before, so just want to make sure, that it's "legal" 😁 )

2022-01-25 09:12 UTC, NorbertAmartus commented on widgets/blueprints/src/TerraformModal.tsx
> +            return resourceLocation.replace(/^[^/]*\//, '');
As the mentioned functionality has been modified, I'm resolving this conversation

2022-01-25 09:12 UTC, kubama approved these changes

2022-01-25 09:14 UTC, kubama commented
> Sure, it seems like a great idea! To be honest, now I'm a little busy with updating the documentation, so I'd merge this PR (as there are no comments on the functionality), to meet the sprint requirements 😁 In the near future, I'll create a PR which would contain an additional test scenario 😉

Cool, approved then 👍.

2022-01-25 09:23 UTC, qooban commented
> In the near future, I'll create a PR which would contain an additional test scenario wink
> @qooban, that would be okay?

Sure, if you plan to do that this week, then perfectly fine 👍🏻  In other case let's have a dedicated ticket for that.

2022-01-25 10:17 UTC, NorbertAmartus commented
Okay, I'm planning to start adding that functionality, before starting working on the tasks from the next sprint, so that we'd have completed this functionality (and that we'd be able to sleep peacefully 😁 )

2022-01-25 10:21 UTC, NorbertAmartus commented
Resolved conflicts with the `master` branch, if that wouldn't be a problem, would you approve once more @qooban, just so the PR could be able to be merged again? 😁

2022-01-25 10:23 UTC, kubama approved these changes

2022-01-25 10:23 UTC, qooban approved these changes

2022-01-25 11:27 UTC, merged