RD-3624 part 3
cloudify-cosmo/cloudify-stage pull request #1812
Opened 2022-02-10 23:35 UTC by leon-good-life

## Description

## Screenshots / Videos

## Checklist

- [ ] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires a documentation update.
- [ ] I added proper labels to this PR.

## Tests

 

## Documentation

2022-02-10 23:51 UTC, leon-good-life commented
I started system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2011/pipeline

2022-02-11 06:17 UTC, leon-good-life commented
I made some fixes and started system tests again:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2013/pipeline

2022-02-11 06:55 UTC, leon-good-life commented
Previous system tests stopped. And I made some changes. So I run system tests again:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2014/pipeline

2022-02-11 07:20 UTC, qooban reviewed
Let's do it step-by-step. I'll review it only after #1770 is merged.

2022-02-13 18:29 UTC, leon-good-life commented
I started system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2033/pipeline

2022-02-13 19:57 UTC, leon-good-life commented
I fixed today eslint fails.
I **fixed** today the following tests:
- `deployments_view_spec`
- one of the tests in `deployment_button_spec`
- two tests in `blueprints_spec`
- `user_spec` test (I run locally this test)

The only test left **to fix**:
- one test in `deployment_button_spec`

2022-02-14 08:13 UTC, leon-good-life commented on test/cypress/support/commands.ts
> +            .get('#loader', { timeout: 21000 })
I added this because user_spec doesn't pass sometimes

2022-02-14 12:22 UTC, qooban requested changes
I did some UI tests and the main thing which is missing is the loading overlay we used to have on clicking "Execute" button in the install workflow execution modal. I added it in the comments. 

There are also few places which seems to need some improvements.

2022-02-14 12:22 UTC, qooban commented on widgets/common/src/GenericDeployModal.tsx
> +    submitExecute() {
I think that:
1. this function should actually be named `onDeployAndInstall` 
2. it should replace the current implementation of `onDeployAndInstall` function
3. you should use `onSubmit` function inside, at least to trigger loading overlay (which is right now missing)

2022-02-14 12:22 UTC, qooban commented on widgets/common/src/GenericDeployModal.tsx
> -import type { AccordionTitleProps } from 'semantic-ui-react';
I think that you can move this file together with `DeployBlueprintModal` to `deployModal` directory at once.

Also, if there are components used only by the code inside `deployModal` directory, they should be moved there as well.

2022-02-14 12:22 UTC, qooban commented on widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
> +    showInstallOptions?: boolean;
Why we need to make it optional?

If that's justified, then probably we should add default value for it, what do you think?

2022-02-14 12:22 UTC, qooban commented on widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
>  } from './types';
If you are doing reordering, I would suggest to sort it alphabetically.

2022-02-14 12:22 UTC, qooban commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
This is quite a change. Will it work properly in both major use-cases:
1. `ExecuteWorkflowModal`
2. `DeployBlueprintModal`
?

2022-02-14 12:58 UTC, leon-good-life commented on test/cypress/support/commands.ts
> +            .get('#loader', { timeout: 21000 })
I addressed it: [86d6b4e](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/86d6b4ea4f21f96b6c400745da74414f55a077de)

2022-02-14 12:59 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
>                  this.setState({ loading: false, errors });
I addressed it: [86d6b4e](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/86d6b4ea4f21f96b6c400745da74414f55a077de)

2022-02-14 12:59 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> -            showInstallModal,
I addressed it: [86d6b4e](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/86d6b4ea4f21f96b6c400745da74414f55a077de)

2022-02-14 14:06 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
I made this change because of TypeScript type errors.

I guess if the system tests pass it means it works properly. doesn't it?

This `executeWorkflow` function that defined here (in `/common/src/executeWorkflow/common.ts`) is being called in two place: `GenericDeployModal` and `ExecuteWorkflowModal`. I looked at the code now and as it was before PR part 2. And it seems okay by looking at the code. Regarding `DeployBlueprintModal` I see it calling `GenericDeployModal`. I will test those use case in the browser.

2022-02-14 15:30 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +        // const deploymentsList: string[] = _.isEmpty(deployments) ? _.compact([deploymentId]) : deployments;
Yes, I verified that we didn't use it in the past, and I removed this line.

2022-02-14 18:25 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +                        // workflow: blueprint.plan.workflows, // TODO: check if adding this line is the correct way to add workflows from blueprint
I checked and verified by comparing of what was before "PR part 2" and by running tests and with console.log(workflow) in multiple places. Commit: [f51b2c2](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/f51b2c2f6cbf943b22a2d06a8a27b1eab847efa4)

2022-02-14 19:29 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
I migrated `DeployBlueprintModal` to TypeScript: [e43c303](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/e43c303b826534f228c32ca360326b22c965a94c)

2022-02-14 19:36 UTC, leon-good-life commented
I started system tests: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2056/pipeline

I addressed carefully 8 out of 11 review comments. I will address the rest tomorrow.

2022-02-14 20:39 UTC, leon-good-life commented
I started system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2057/pipeline

2022-02-14 20:47 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
> +    showInstallOptions?: boolean;
I converted `showInstallOptions ` to be a required prop: 1cb737a

2022-02-14 20:52 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +        if (typeof workflow === 'string') {
I will check it again

2022-02-14 21:40 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +    submitExecute() {
I think that I addressed point 3 too, because it now calls `onSubmit`, I debugged it and saw each step - a total of 4. I also looked at the steps that passed in DeployBlueprintModal. And I saw in the UI something like "Loading step 1/4 ......".

 But I still suspect that something may be missing because `deployment_button_spec` is falling when the test tries to verify that the loading is hidden after it visible for a few seconds.

2022-02-14 22:20 UTC, leon-good-life commented
> I started system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2057/pipeline


✅ 61 out of 63 system tests passed!

The only system tests that didn't pass are:
- user_spec - "element is above error" I think this test just randomly didn't pass, maybe if I'll just run it again it will pass
- deployment_button_spec -  is falling when the test tries to verify that the loading is hidden after it visible for up to 40 seconds:
```
    const waitForDeployBlueprintModal = (install = false) => {
        const deployTimeout = 30000;
        const deployAndInstallTimeout = 40000;

        cy.get('div.deployBlueprintModal div.ui.text.loader').as('loader');
        cy.get('@loader').should('be.visible');
        // The test is falling in the next line:
        cy.get('@loader', { timeout: install ? deployAndInstallTimeout : deployTimeout }).should('not.exist');
    };

2022-02-14 22:21 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
I refactored this code: [cbbcd79](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/cbbcd79ee2b4eab5ac215d9155944372db87d78f)

I will check it on 15th of Feb.

2022-02-15 06:25 UTC, leon-good-life commented
System tests after refactoring executeWorkflow (removing setErrors and using Promise) cbbcd79ee2b4eab5ac215d9155944372db87d78f: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2058/pipeline

2022-02-15 06:32 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +        if (typeof workflow === 'string') {
Yesterday I changed to:
```
    componentDidMount() {
        const { DeploymentActions } = Stage.Common;
        const { toolbox } = this.props;
        const { workflow, deploymentId } = this.state;
        const actions = new DeploymentActions(toolbox);
        const workflowName = getWorkflowName(workflow);
        this.setState({ loading: true });
        actions
            .doGetWorkflows(deploymentId)
            .then(({ workflows }: { workflows: unknown[] }) => {
                const selectedWorkflow = _.find(workflows, {
                    name: workflowName
                }) as { parameters: BaseWorkflowInputs };
                if (selectedWorkflow) {
                    this.setWorkflowParams(selectedWorkflow);
                } else {
                    this.setState({
                        errors: tExecute('errors.workflowError', {
                            deploymentId,
                            workflowName
                        })
                    });
                }
            })
            .finally(() => this.setState({ loading: false }));
    }
```

But, maybe the following:
```

    componentDidMount() {
        const { workflow } = this.state;
        this.setWorkflowParams(workflow);
    }
```
is the right way to go and not what I did yesterday. I will compare to what was before PR part 2.

2022-02-15 09:07 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +        if (typeof workflow === 'string') {
I removed the current code. Instead I extracted and set baseWorkflowParams and userWorkflowParams from workflow in componentDidMount: [0823ead](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/0823ead7b5c32208faa1a61d0c9edc91cebbcb83)

2022-02-15 10:04 UTC, leon-good-life commented
I fixed all the tests and started system tests: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2069/

2022-02-15 10:05 UTC, leon-good-life commented on widgets/common/src/GenericDeployModal.tsx
> +    submitExecute() {
I fixed it: [31d5da2](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/31d5da2744cfff726b6007172f58a15fea04aa1f)

2022-02-15 10:56 UTC, leon-good-life commented
There were strange errors in the system tests: `minutesToMs is not a function`  in `support/plugins.ts` file.

I run the tests again, hopefully there will be no errors:
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2071/

2022-02-15 11:01 UTC, qooban commented
> There were strange errors in the system tests: `minutesToMs is not a function` in `support/plugins.ts` file.
> 
> I run the tests again, hopefully there will be no errors: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2071/

Please check #cfydevs-ui Slack channel. It's due to my recent PR. Don't bother about it.

2022-02-15 11:12 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
I looked how the code was in the past. There was a function that returned boolean and Promise. But all the code that called that function treated it like a void function and didn't expect any returned values from it. 

I refactored the code so instead of passing setErrors function, I'm calling `executeWorkflow` function and use `catch`. `executeWorkflow` returns a promise only.

2022-02-15 11:15 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject();
In `DeployBlueprintModal` this part certainly working now as it is my main test case.

2022-02-15 11:49 UTC, leon-good-life commented
System tests after merging with master: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2073/pipeline

2022-02-15 11:57 UTC, qooban reviewed
Added few more comments. Most important area is to figure out if blueprints with custom `install` workflows are working properly.

Did UI tests:
1. Loading overlay seems to work. Great 👍🏻 
2. Spotted small issue with dropdown button. It should be disabled after submission. See video:
https://user-images.githubusercontent.com/5202105/154057457-0ffa6238-186c-4ecc-9839-85c0605e9489.mp4

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/DeployBlueprintModal.tsx
> -// @ts-nocheck File not migrated fully to TS
Great that you managed to migrate it 🎉

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/DeployBlueprintModal.tsx
> +import { WorkflowParameters } from '../executeWorkflow';
Optional:

I guess we can use `import type` for `BlueprintDeployParams`, `WorkflowOptions` and `WorkflowParameters`.

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject(error);
Optional:

```suggestion
        return Promise.reject(t('errors.missingWorkflow'));
```

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject(error);
Optional:

```suggestion
        return Promise.reject(t('errors.missingDeployment'));
```

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    message?: string;
Is there a case when `message` is `undefined`?

2022-02-15 11:57 UTC, qooban commented on test/cypress/integration/widgets/deployment_button_spec.ts
>              }
I think it make sense to add a test checking if for a blueprint with custom `install` workflow (with some parameters), the workflow parameters are displayed in `Install` section. WDYT?

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    deploymentParameters: BlueprintDeployParams,
I see the change here in types, could you elaborate on that?
I'm not saying it's bad or not, I'm just wondering what is there behind that change.

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    userWorkflowParams: UserWorkflowInputsState;
I'm wondering shouldn't we change the names to indicate more precisely what kind of workflow we are using here:
```suggestion
    installWorkflow: Workflow;
    baseInstallWorkflowParams: BaseWorkflowInputs;
    userInstallWorkflowParams: UserWorkflowInputsState;
```

In the context of `GenericDeployModal` there cannot be any other workflow, am I correct?

2022-02-15 11:57 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +        workflow: GenericDeployModal.initialInstallWorkflow,
What if we have custom `install` workflow implemented for the blueprint selected to be deployed?
Will it work (custom `install` workflow's parameters displayed in Install section) with the current solution?

2022-02-15 11:59 UTC, leon-good-life commented on widgets/common/src/deployModal/DeployBlueprintModal.tsx
> -// @ts-nocheck File not migrated fully to TS
Thank you 🙂

2022-02-15 12:10 UTC, leon-good-life commented on widgets/common/src/deployModal/DeployBlueprintModal.tsx
> +import { WorkflowParameters } from '../executeWorkflow';
I changed to `import type`: [d2bfdab](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/d2bfdab9a8493e290cc21d1903d3cae53bfae637)

2022-02-15 12:13 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject(error);
changed: 029fbe5

2022-02-15 12:18 UTC, leon-good-life commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    message?: string;
![Screen Shot 2022-02-15 at 14 14 46](https://user-images.githubusercontent.com/17104212/154060636-82d75a8f-3c84-4743-9300-e367f129f7b2.png)
![Screen Shot 2022-02-15 at 14 17 47](https://user-images.githubusercontent.com/17104212/154060646-bed35078-ed4e-46cd-8dc8-d24ae706d5b5.png)

2022-02-15 12:19 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
>              }
I think it is a good idea, I also thought about it, I will add soon.

2022-02-15 12:30 UTC, leon-good-life commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    userWorkflowParams: UserWorkflowInputsState;
I added `install` prefix: [daa561f](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/daa561f4a97f0ae1e757180a6b800d71b8cd9212)

2022-02-15 12:37 UTC, leon-good-life commented on widgets/common/src/executeWorkflow/common.ts
> +        return Promise.reject(error);
changed: [078b8aa](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/078b8aadc70f9ec5873805afba5da7bdc1bb31e2)

2022-02-15 12:40 UTC, leon-good-life commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +    deploymentParameters: BlueprintDeployParams,
Regarding L36, it was `PreviousStepOutcome: any`. But the function can receive also a `deploymentId: string`, so I combined them both into: `deploymentIdOrPreviousStepOutcome: string | any`.

2022-02-15 14:22 UTC, leon-good-life commented
> Spotted small issue with dropdown button. It should be disabled after submission.

I fixed it. Now, I'm disabling the DropDown when Install or Deploy is clicked: [22b07d2](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/22b07d227a4629ac47fd87ea7344082cc4a35f80)

2022-02-15 15:19 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
>              }
I guess I need to add a blueprint with:
```
workflows:

  install:
    mapping: default_workflows.cloudify.plugins.workflows.install
    is_cascading: false
    parameters:
      xxx:
        default: blabla
```

2022-02-16 18:06 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
>              }
I added system test: [bd30cda](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/bd30cda2fcd059193064595d18a2dea83aa8270e)

2022-02-16 18:08 UTC, leon-good-life commented
I started system tests:
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/

2022-02-17 07:09 UTC, qooban reviewed
Thanks for updates. We are getting closer 🙂 

Added two comments.

Seems like system tests on your branch after recent changes are failing: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2077/

2022-02-17 07:09 UTC, qooban commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +    it('blueprint with custom install workflow', () => {
1. I'm wondering why you decided to create another test case instead of extending 'allows to deploy and install a blueprint'? I'm not saying it's bad or good.

2. If you are willing to keep this test case, then to be inline with the naming convention I think the better would be to name it:
```suggestion
    it('allows to set install workflow parameters', () => {
```

3. Setting parameters is one thing, but maybe worth to check if they are passed down to the manager also? You could also change some of the toggles.

2022-02-17 07:09 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +                        ),
Seems like it is duplicated, maybe worth to extract function for it?

2022-02-17 09:49 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +    it('blueprint with custom install workflow', () => {
when I combine a `simple` blueprint:
```
tosca_definitions_version: cloudify_dsl_1_3

description: >
  This is very simple blueprint

imports:
  - http://www.getcloudify.org/spec/cloudify/5.0.5/types.yaml

inputs:
  server_ip:
    description: >
      The ip of the server the application will be deployed on.
    display_label: Server IP
  hidden:
    hidden: true
    default: 0

node_templates:
  vm:
    type: cloudify.nodes.Compute
    properties:
      ip: { get_input: server_ip }
```
with `custom install workflow parameters` blueprint:
```
tosca_definitions_version: cloudify_dsl_1_3

plugins:
    default_workflows:
        executor: central_deployment_agent
        install: false

workflows:
    install:
        mapping: default_workflows.cloudify.plugins.workflows.install
        is_cascading: false
        parameters:
            xxx:
                default: blabla
            yyy:
                default: blabla
```
I'm getting this blueprint:
```
tosca_definitions_version: cloudify_dsl_1_3

description: >
  This is very simple blueprint

imports:
  - http://www.getcloudify.org/spec/cloudify/5.0.5/types.yaml

inputs:
  server_ip:
    description: >
      The ip of the server the application will be deployed on.
    display_label: Server IP
  hidden:
    hidden: true
    default: 0

node_templates:
  vm:
    type: cloudify.nodes.Compute
    properties:
      ip: { get_input: server_ip }

plugins:
  default_workflows:
    executor: central_deployment_agent
    install: false

workflows:
  install:
    mapping: default_workflows.cloudify.plugins.workflows.install
    is_cascading: false
    parameters:
      xxx:
        default: blabla
      yyy:
        default: blabla
```
But I do not get the workflow parameters from the concatenated blueprint.
I'm afraid to waste too much time on modifying the blueprint. So my solution will be to use the current blueprint I have. I will combine the tests.

2022-02-17 10:00 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +    it('blueprint with custom install workflow', () => {
I address points 1 and 2 (I combined the tests): [ad275d1](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/ad275d1784457a61f414f5ace897fc0f7b4b115f)

I'm working now on point 3: to verify changing and saving `custom install workflow parameters` and `dry run`

2022-02-17 10:30 UTC, leon-good-life commented
> Seems like system tests on your branch after recent changes are failing: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2077/

I started a system test that was failed: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2079/pipeline

2022-02-17 10:33 UTC, qooban commented
> > Seems like system tests on your branch after recent changes are failing: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2077/
> 
> I started `deployment_button_spec` system test - the test that was failed: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2079/pipeline

Seems like you disabled (commented out) some tests in `deployment_button_spec`, so the results may not be reliable.

2022-02-17 10:41 UTC, leon-good-life commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +    it('blueprint with custom install workflow', () => {
I addressed point 3:
- [48d8a2d](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/48d8a2d816fd6ff323940c556607703c2183c5fd)
- [8b728c4](https://github.com/cloudify-cosmo/cloudify-stage/pull/1812/commits/8b728c4119f8a5d530235a4f3a51049ee2e3d889)

2022-02-17 10:45 UTC, leon-good-life commented
> Seems like you disabled (commented out) some tests in deployment_button_spec, so the results may not be reliable.

I committed commented out code by mistake. I resolved the comment regarding test and I'm running system test again:
test/cypress/integration/widgets/deployment_button_spec.ts: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2080/pipeline

2022-02-17 11:08 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +        this.setState({ activeSection: -1, loading: true, errors: {} });
Why do we need it? (same in L400)

2022-02-17 11:08 UTC, qooban commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +            expect(response.body.items[0].parameters['yyy']).to.be.equal('world');
Linter is complaining about this lines (see `npm run lint`).

Optional:

What about having consts defined for parameter names? They are used in 2 places - when you fill inputs and here where you check if they are passed properly.

2022-02-17 11:22 UTC, leon-good-life commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +                        ),
I created the following locally, but I'm getting lint error:
<img width="1008" alt="Screen Shot 2022-02-17 at 13 18 32" src="https://user-images.githubusercontent.com/17104212/154471026-9acd40e4-4ec6-47c9-b956-6d5e3f022f53.png">
<img width="1301" alt="Screen Shot 2022-02-17 at 13 19 06" src="https://user-images.githubusercontent.com/17104212/154471014-1b3c447b-260b-47c6-8d10-cbedfb0699c1.png">
<img width="1212" alt="Screen Shot 2022-02-17 at 13 21 12" src="https://user-images.githubusercontent.com/17104212/154471291-6edf99b0-9c3d-4d1f-9f83-44305dfabba6.png">

As it optional, I will focus on other comments.

2022-02-17 11:30 UTC, leon-good-life commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +        this.setState({ activeSection: -1, loading: true, errors: {} });
<img width="1373" alt="Screen Shot 2022-02-17 at 13 27 27" src="https://user-images.githubusercontent.com/17104212/154472726-6e20ff4d-1b96-48c6-bab5-ad7c24560bcf.png">

2022-02-17 11:36 UTC, qooban commented on widgets/common/src/deployModal/GenericDeployModal.tsx
> +        this.setState({ activeSection: -1, loading: true, errors: {} });
OK 👍🏻

2022-02-17 11:38 UTC, qooban approved these changes
Please verify that all system tests are passing before merging this PR.

2022-02-17 11:38 UTC, qooban commented on test/cypress/integration/widgets/deployment_button_spec.ts
> +            expect(response.body.items[0].parameters.yyy).to.be.equal(customInstallWorkflowParam2);
Optional

Actually I was thinking to have consts for `xxx` and `yyy` 🙂 And not necessarily values.

2022-02-17 11:46 UTC, leon-good-life commented
> Please verify that all system tests are passing before merging this PR.

sure, I wait for Yuval, he upgrading the Jenkins right now

2022-02-17 13:04 UTC, leon-good-life commented
I started system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2082/pipeline

2022-02-17 14:42 UTC, leon-good-life commented
Apart of https://cloudifysource.atlassian.net/browse/RD-4286 that is failing on master branch, All system tests passed. I will merge this PR.

2022-02-17 14:42 UTC, merged