RD-4577: Fix for inproper Content-Type header in requests in Safari and Chrome browsers
cloudify-cosmo/cloudify-stage pull request #1884
Opened 2022-03-23 11:49 UTC by jawamartus

## Description

https://cloudifysource.atlassian.net/browse/RD-4577

## Screenshots / Videos

## Checklist

- [ ] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [ ] I added proper labels to this PR.

## Tests

 

## Documentation

2022-03-23 12:00 UTC, qooban commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 header field names are case-insensitive. We didn't have problems due to that before.

Is that really a problem? Can you point out a place where Safari and Chrome browsers are not supporting lower-cased headers?

2022-03-23 12:04 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
It's not related to the size of the letters in HTTP request header field name. Please read the bug description. I tested the PR it removes the bug.

2022-03-23 12:55 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
In the future we may consider a refactoring of this part of our app where we pass json to options.headers. We may use Headers object instead which is dedicated to this purpose.

It may require a lot of work and testing and it's not in the scope of this PR I think.

2022-03-23 12:56 UTC, qooban requested changes

2022-03-23 12:57 UTC, qooban commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
> It may require a lot of work and testing and it's not in the scope of this PR I think.

Please create ticket for that then and let me know about the ID.

2022-03-23 12:58 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
I think it would still make a space for the other related bugs. What do you think about using Headers object instead of passing json to the headers?

2022-03-23 13:07 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
The problem has been solved in proposed solution. What "whole problem" do you mean?

2022-03-23 13:13 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
> Is that really a problem? Can you point out a place where Safari and Chrome browsers are not supporting lower-cased headers?

Answering your question. Safari and Chrome are supporting case-insensitive headers. However in different way.

Regarding first question. What do you mean by "that"? The proposed solution? Yes it's fixing the bug.

2022-03-23 13:31 UTC, qooban commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
I guess it'd be easier to have a chat f2f tomorrow morning to discuss all of that 🙂 
Scheduled it (let me know if the time is OK).

2022-03-23 13:40 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
I created a ticket you requested: https://cloudifysource.atlassian.net/browse/RD-4579

2022-03-24 08:24 UTC, qooban approved these changes

2022-03-24 08:24 UTC, qooban commented on widgets/common/src/DynamicDropdown.tsx
> -                    headers: {
Oh, so no need to pass it? Even better I think 🙂

2022-03-24 08:25 UTC, jawamartus commented on app/utils/External.ts
> +    return { 'Content-Type': type || 'application/json' };
Solution changed. Tested manually in Firefox and Chrome.

2022-03-24 08:45 UTC, qooban commented
@jawamartus Once https://github.com/cloudify-cosmo/cloudify-stage/pull/1886 is merged, you should be able to get green CI.

2022-03-24 09:19 UTC, merged