RD 273
cloudify-cosmo/cloudify-stage pull request #1908
Opened 2022-04-05 12:28 UTC by bartoszkosciug

RD-273
https://cloudifysource.atlassian.net/browse/RD-273

## Description
The change that was need is to add the update artifacts to s3 bucket functionality to the pipeline workflow.

## Screenshots / Videos
N/A

## Checklist
N/A
the change is not UI related

## Tests
N/A

## Documentation
N/A

2022-04-05 14:04 UTC, yuvlar requested changes
Looks good, left some comments for changes

2022-04-05 14:04 UTC, yuvlar commented on jenkins/Jenkinsfile
> -                curl -fO "${CFY_MANAGER_URL}/${BRANCH}/packaging/version_info"
why change this one? the version should be fetched according to the running branch.
The thing is though, that if there's no such branch in cloudify-manager repo, it'll fail - but it should enter this stage only if it's *-build | master, so it shouldn't be a problem

2022-04-05 14:04 UTC, yuvlar commented on jenkins/jenkins2
> +@Library('pipeline-shared-library') _
I believe this file was only for testing?

2022-04-05 14:33 UTC, bartoszkosciug commented on jenkins/Jenkinsfile
> -                curl -fO "${CFY_MANAGER_URL}/${BRANCH}/packaging/version_info"
back to the original way of fetching [fdd2a59]

2022-04-05 14:34 UTC, bartoszkosciug commented on jenkins/jenkins2
> +@Library('pipeline-shared-library') _
removed from the pr

2022-04-06 06:28 UTC, qooban reviewed
Added some comments.

Regarding checklist and:

> the change is not UI related

we often add non-UI related changes to this repo and we always fill the checklist, so I think it would be good to have it still. Labels, documentation updates and tests are not only related to frontend code updates. See other PRs.

2022-04-06 06:28 UTC, qooban commented on jenkins/build-pod.yaml
> +  - name: awscli
I assume adding new container won't affect overall job performance?
(as it will be used only specific branches, we don't want to have slow down on development branches)

2022-04-06 06:28 UTC, qooban commented on jenkins/Jenkinsfile
> +    PRERELEASE = getPreRelease(PROJECT,"${env.BRANCH_NAME}").trim()
In "Build RPM" stage there is different method used to get version and release. 

I guess it works like that:
1. Fetch `version_info` - `curl -fO "${CFY_MANAGER_URL}/${BRANCH}/packaging/version_info"`
2. Source `version_info` - line with `cd ~/rpmbuild/BUILD && source ./version_info`
3. Use env vars created during sourcing - `CLOUDIFY_VERSION`, `CLOUDIFY_PACKAGE_RELEASE`

Shouldn't we align it and use only one method in both cases?

2022-04-06 08:20 UTC, yuvlar commented on jenkins/build-pod.yaml
> +  - name: awscli
Shouldn't interfere, like you said, it'll be used only once and won't affect the overall job performance.

2022-04-06 08:22 UTC, yuvlar commented on jenkins/Jenkinsfile
> +    PRERELEASE = getPreRelease(PROJECT,"${env.BRANCH_NAME}").trim()
@qooban I agree with you that there's no benefit in using two different methods to get the same vars.
But in order to have those env vars available for RPM uploading, it's best to pull them in the beginning of the pipeline, and update the "Build RPM" stage to use the $VERSION & $PRERELEASE that we created in the beginning.
@bartoszkosciug Please change it accordingly

2022-04-06 12:04 UTC, qooban commented on jenkins/build-pod.yaml
> +  - name: awscli
Good 👍🏻

2022-04-06 12:04 UTC, qooban commented on jenkins/Jenkinsfile
> +    PRERELEASE = getPreRelease(PROJECT,"${env.BRANCH_NAME}").trim()
Yeah, make sense. Thanks for making the changes.

2022-04-06 12:05 UTC, qooban approved these changes
From my perspective looks good. Let's wait for @yuvlar confirmation.

2022-04-06 12:41 UTC, bartoszkosciug commented on jenkins/Jenkinsfile
> +          post {
in examples the path will be cloudify-release-eu/cloudfy/6.4.0/.dev1-build/cloudify-stage/13 
and cloudify-release-eu/cloudfy/6.4.0/.dev1-build/cloudify-stage/latest

2022-04-06 14:17 UTC, yuvlar approved these changes

2022-04-06 14:44 UTC, merged