RD-4844: Update all marketplaces to 6.4
cloudify-cosmo/cloudify-stage pull request #1990
Opened 2022-06-01 13:34 UTC by PatrycjaKubiczek

## Description

[RD-4844](https://cloudifysource.atlassian.net/browse/RD-4844)

- update URLs to point to 6.4.
- change the default number of tabs from 6 to 13 in `blueprintMarketplaceTabsConfig.ts`
- add custom style to `Tabs.tsx` to display all tabs inside modal

## Screenshots / Videos

![PR-3](https://user-images.githubusercontent.com/17828621/171415218-d756e894-5b55-4818-aa1c-2d86b4f3461e.jpg)
![PR-2](https://user-images.githubusercontent.com/17828621/171415229-6b412a94-d936-4b6b-8c37-551d523ca36b.jpg)
![PR-4](https://user-images.githubusercontent.com/17828621/171416197-770a524d-43d7-4e34-b7a7-90efd1ca4ab3.jpg)

important note - currently, on 3 tabs (Docker, Ansible & Other) we could have a problem with access so it will looks like this, but it will be fixed:  
![Zrzut ekranu 2022-06-01 134706](https://user-images.githubusercontent.com/17828621/171415468-842ce8f4-7ba2-4d24-82c0-ef7588c40399.jpg)

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

## Documentation

2022-06-02 12:47 UTC, qooban commented
@PatrycjaKubiczek I won't be able to review it before my vacation, so I have removed myself and added @kubama 🙂 Good luck!

2022-06-03 07:10 UTC, NorbertAmartus commented
@kubama 
> I think having a scrollbar for tabs looks quite awkward. Did you consider extending the modal's width so the scrollbar wasn't needed, at lest in cases when horizontal screen resolution would allow it?

I just did a quick check on how it'd look on 1280px width screen (our minimum supported width):
![image](https://user-images.githubusercontent.com/89005877/171803723-207a2227-fb95-475b-995b-2dade6ff7bab.png)

It still fits, but barely 😅 
So having in mind that marketplace is lately being frequently updated, the universal solution may be a good option

Another thing, which may be against a pixel-adjusted solution, is that the `Modal` component max-width may be adjusted with the usage of the following prop:
```typescript
size?: 'mini' | 'tiny' | 'small' | 'large' | 'fullscreen'
``` 

So, as showned at the screenshot above, we'd need to go with the `fullscreen` option, which may not be ideal for all of the screen sizes

Another option would be to override `<Modal />` styles using `className` property with a very specific selectors / `!important` flag, which seems to not be an ideal solution 😅 

WDYT?
Maybe it should be discussed with Ilan? 🤔

2022-06-03 07:24 UTC, NorbertAmartus requested changes

2022-06-03 07:24 UTC, NorbertAmartus commented on widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
> +const defaultNumberOfTabs = 13;
There is [a neat option](https://www.i18next.com/translation-function/objects-and-arrays) to extract an `object`/`array` from the `i18n` 

We could try to use it here, just so we wouldn't need to remember about adjusting this number in the future 💪 

```suggestion
import { times, size } from 'lodash';

const t = Stage.Utils.getT(`widgets.blueprints.configuration.marketplaceTabs`);
const defaultNumberOfTabs = size(t('columns.defaultValues', { returnObjects: true }));
```

2022-06-03 08:32 UTC, PatrycjaKubiczek commented
@NorbertAmartus I'm afraid it won't fit on 1280px resolution with fullscreen class on modal
![tabs](https://user-images.githubusercontent.com/17828621/171818178-4afa8b5b-7097-4c2e-8bd9-da582c91de9b.jpg)
I think I needed to add "Getting Started" column as well? 🤔 

beside it won't look good on larger screens  :( 
![tabs-3](https://user-images.githubusercontent.com/17828621/171818663-9c9d87c5-6a15-4900-889e-c13295f6f59a.jpg)

the option "large" doesn't fit neither
![tabs-3](https://user-images.githubusercontent.com/17828621/171818696-45908e5c-9ec2-40e8-8578-be87b4f69709.jpg)

I will try some other options

2022-06-03 09:10 UTC, kubama commented
If we can't fit it then I would say we should consider a different approach. I think scroll is not the best option here, I would rather consider something like this:
![image](https://user-images.githubusercontent.com/49753069/171825150-2242094a-0e35-4a0e-b950-acc9ef121ef0.png)

2022-06-03 11:52 UTC, PatrycjaKubiczek commented
@kubama I tried quickly reproduce this solution in our product. I'm wondering if this 
![tabs-work](https://user-images.githubusercontent.com/17828621/171847039-ed696666-6fad-4e1e-9aa3-768da090c3f4.jpg)
it would probably also need extra work on adjusting editMode

I also tried some different approach - create a wrapper around tabs, imo it doesn't look perfect as well... :( but it's kinda bulletproof on a different resolutions? WDYT @NorbertAmartus @kubama ?
![tabs-different](https://user-images.githubusercontent.com/17828621/171847605-e89ab2cf-8e66-4921-944a-d863a4e00fb5.jpg)

2022-06-03 12:05 UTC, kubama commented
@PatrycjaKubiczek Ah, yes, I didn't consider edit mode. Changes there would be definitely out of scope of this ticket.

I think your second suggestion (with second row of the tabs) is still better than having a scroll.

2022-06-03 13:21 UTC, kubama commented
> do you think that we should ping PM's about that kind of `<Tabs />` adjustment, so that they'd be aware of it?

Sure, lets let them now.

2022-06-06 07:20 UTC, PatrycjaKubiczek commented on widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
> +const defaultNumberOfTabs = 13;
done 👌

2022-06-06 09:06 UTC, PatrycjaKubiczek commented
I update the CSS of tabs a bit, so it looks better but it would still look like a tab
![Zrzut ekranu 2022-06-06 103607](https://user-images.githubusercontent.com/17828621/172130945-a2eecee3-0823-4c94-8b4a-2ae59e7e7b44.jpg)
![Zrzut ekranu 2022-06-06 103623](https://user-images.githubusercontent.com/17828621/172130950-68e5b561-80dd-4380-8f34-b67a78fb486d.jpg)

2022-06-06 12:36 UTC, NorbertAmartus commented
I've just had a call with Ilan about the attached results and he said, that for the time being, it's prefect 🚀 
Just wanted to notify about it, as it's being consider a right direction 🎉

2022-06-06 13:40 UTC, NorbertAmartus submitted a review, later dismissed
Looks great 💪 
Thanks for addressing all of the comments and for putting extra work on adjusting `Tabs` styling! 🎸

2022-06-06 13:48 UTC, kubama approved these changes

2022-06-08 10:34 UTC, NorbertAmartus approved these changes
Looks good to me 🎉

2022-06-08 10:41 UTC, merged