RD-5437 Redirect to the blueprint page after blueprint upload
cloudify-cosmo/cloudify-stage pull request #2117
Opened 2022-08-03 08:54 UTC by leon-good-life

## Description

## Screenshots / Videos

## Checklist

- [ ] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [ ] I added proper labels to this PR.

## Tests

 

## Documentation

2022-08-03 09:19 UTC, kubama submitted a review, later dismissed
No system test update is necessary?

2022-08-03 09:33 UTC, qooban requested changes
Wait, it is stated that "User should be navigated to the uploaded blueprint page and be presented with the deployment modal" in RD-5437. 

Is deployment modal presented to the user? I guess not as there's no `openDeploymentModal` used as suggested in the ticket. 

System tests (for blueprints widget at least) would require an update I think. If not, I would add a test to check if the user gets redirected.

2022-08-03 09:50 UTC, leon-good-life commented
I addressed the review comment - open deployment modal: [56d63e9](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/56d63e92deacf2fded07a7724abddd476ab007ce)

https://user-images.githubusercontent.com/17104212/182579031-ecc3521b-dc88-45cd-9702-f8af618ea3d2.mov

2022-08-03 09:52 UTC, leon-good-life commented
I'm working on updating the `blueprints_spec`.

2022-08-03 10:19 UTC, leon-good-life commented
I fixed and started `blueprints_spec`: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3326/pipeline

2022-08-03 10:26 UTC, leon-good-life commented
I'm making changes and fixes in `blueprints_spec`.

2022-08-03 14:57 UTC, leon-good-life commented
I started `blueprint_spec`:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3331/pipeline

2022-08-04 10:19 UTC, kubama commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
Duplicated lines 346-348

2022-08-04 10:19 UTC, kubama commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('.deployBlueprintModal').within(() => cy.contains('Cancel').click());
```suggestion
                cy.get('.deployBlueprintModal').contains('Cancel').click();
```

2022-08-04 10:19 UTC, kubama commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
Why do we need to call `usePageMock` here?

2022-08-04 10:31 UTC, qooban commented on test/cypress/integration/widgets/blueprints_spec.ts
>                  getBlueprintRow(blueprintName).contains('read-secret-blueprint.yaml');
If we want to check blueprint YAML file name, instead of getting back to the Blueprints page, maybe we can check it on the blueprint page (the one to which user was already redirected)? There's "Blueprint Sources" widget that keeps that information.

Same comment applies to the second test - L362-L363.

2022-08-04 10:31 UTC, qooban commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('.deployBlueprintModal').within(() => cy.contains('Cancel').click());
Optional:

You possibly can have more elegant solution following Cypress best practices here (see https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) if you try to minimize using CSS classes to get elements.

You can check the solution from `test/cypress/integration/widgets/blueprints_terraform_spec.ts` and have sth like:
```
cy.contains('Deploy blueprint')
    .parent('.modal')
    .within(() => cy.contains('Cancel').click())
```
WDYT?

2022-08-05 08:47 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
I addressed it: [9e8477e](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/9e8477e8669a814a4bd4caecb9cd1407b234ce68)

2022-08-05 08:47 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('.deployBlueprintModal').within(() => cy.contains('Cancel').click());
I addressed it: [9e8477e](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/9e8477e8669a814a4bd4caecb9cd1407b234ce68)

2022-08-05 08:48 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
Because I want to redirect back to blueprints. Maybe `cy.visit` is better? I can try.

2022-08-05 09:06 UTC, kubama commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
We already call `usePageMock` with same parameters in `beforeEach`, is it necessary to repeat it?

2022-08-05 09:11 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
I will use "Blueprint Sources"  widget

2022-08-07 12:35 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.usePageMock('blueprints', blueprintsWidgetConfiguration).refreshTemplate();
I removed this line: [27d8149](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/27d81499edaaa968c6dfb0f492e4e780ab4d76e5)

2022-08-07 12:35 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
>                  getBlueprintRow(blueprintName).contains('read-secret-blueprint.yaml');
[27d8149](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/27d81499edaaa968c6dfb0f492e4e780ab4d76e5)

2022-08-07 13:00 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('.deployBlueprintModal').within(() => cy.contains('Cancel').click());
I used your suggestion: [5b4bd27](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/5b4bd27031ea7d071ad425c887b457d45050343e)

2022-08-07 13:02 UTC, leon-good-life commented
I started `blueprints_spec`: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3392/pipeline

2022-08-07 13:15 UTC, leon-good-life commented
The test passed

2022-08-08 10:03 UTC, kubama commented on test/cypress/integration/widgets/blueprints_spec.ts
> +        describe.only('should upload a blueprint', () => {
`only` :slightly_smiling_face:

2022-08-08 10:05 UTC, kubama submitted a review, later dismissed
I think system test should be rerun after removing `only`. Other than that it looks good to me :+1: .

2022-08-08 10:17 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +        describe.only('should upload a blueprint', () => {
I removed it: c0c25a3

2022-08-08 10:19 UTC, leon-good-life commented
I started `blueprints_spec`: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3397/pipeline

2022-08-08 10:22 UTC, qooban commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('[role="treeitem"]').contains('read-secret-blueprint.yaml');
The verification right now is less strict than previously as it doesn't verify if the YAML file is the main YAML file of that blueprint.

To narrow down the context and search only in Blueprint Sources widget, you can use `cy.getWidget('blueprintSources')`. To find main YAML file element in the list you probably can use something like `cy.contains('Main').parent()`.

2022-08-08 11:05 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.get('[role="treeitem"]').contains('read-secret-blueprint.yaml');
I addressed it: c2491e9

2022-08-08 11:06 UTC, leon-good-life commented
I started system tests again: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3398/pipeline

I verified that they passing locally.

2022-08-08 11:14 UTC, qooban submitted a review, later dismissed
Thx for additional effort.

2022-08-08 11:14 UTC, qooban commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.getWidget('blueprintSources').contains('Main').parent().contains('read-secret-blueprint.yaml');
It could also be extracted to a function as you are doing the same in L365.

2022-08-08 11:34 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.getWidget('blueprintSources').contains('Main').parent().contains('read-secret-blueprint.yaml');
I wonder how to call the function, maybe `blueprintSourceMainFile`?

2022-08-08 11:37 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +                cy.getWidget('blueprintSources').contains('Main').parent().contains('read-secret-blueprint.yaml');
[0dc295e](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/0dc295e31861d0672852a2a890f762c0e04bc0c9)

2022-08-08 11:39 UTC, leon-good-life commented
The test passed.

I run it again after addressing the last review comment:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3401/pipeline

2022-08-08 11:50 UTC, qooban commented on test/cypress/integration/widgets/blueprints_spec.ts
> +    function blueprintSourceMainFile() {
Function names are typically verbs or verb phrases, so I would go with something like `getBlueprintMainFile` or `getBlueprintYamlFile` or `getBlueprintMainYamlFile`.

2022-08-08 11:54 UTC, leon-good-life commented on test/cypress/integration/widgets/blueprints_spec.ts
> +    function blueprintSourceMainFile() {
I renamed it: [2924a43](https://github.com/cloudify-cosmo/cloudify-stage/pull/2117/commits/2924a43759b9e8617fdfaf878f4e9622ffc7dcd9)

2022-08-08 11:57 UTC, qooban approved these changes

2022-08-08 12:05 UTC, merged