RD-5771 Migrate Resource Filter widget
cloudify-cosmo/cloudify-stage pull request #2450
Opened 2023-02-22 12:22 UTC by leon-good-life

## Description

## Screenshots / Videos

## Checklist

- [ ] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [ ] I added proper labels to this PR.

## Tests

 

## Documentation

2023-02-24 09:08 UTC, kubama requested changes

2023-02-24 09:08 UTC, kubama commented on widgets/filter/src/Filter.tsx
> +            if (configuration[configurationKey as keyof FilterWidgetConfiguration]) {
Similarly here, can we make `configurationKey` a typed variable to avoid casting?

2023-02-24 09:08 UTC, kubama commented on widgets/filter/src/Filter.tsx
> +                const { [stateKey as keyof FilterState]: value } = this.state;
... and here

2023-02-24 09:08 UTC, kubama commented on widgets/filter/src/Filter.tsx
> +                const url = `/${fetchManagerEndpoint || `${entityName?.replace(' ', '-').toLowerCase()}s`}`;
`||` is changed go `??` twice here. This changes the logic as in both cases left-hand value can be an empty string. Are you sure this is a safe change?

2023-03-01 09:24 UTC, leon-good-life commented on widgets/filter/src/widget.tsx
>      description: 'Adds a filter section for resources - blueprints, deployments, nodes, node instances and executions',
I added translations: [ed67045](https://github.com/cloudify-cosmo/cloudify-stage/pull/2450/commits/ed67045c8d90dc7786f3b875664d417642210628)

2023-03-01 09:28 UTC, leon-good-life commented on widgets/filter/src/Filter.tsx
> +        if (!allowMultipleSelection && selectedDeploymentId && selectedNodeId) {
I fixed it: [9d9cfb7](https://github.com/cloudify-cosmo/cloudify-stage/pull/2450/commits/9d9cfb7f3a4a43e2048733616d4ab612cafee84e)

2023-04-12 06:43 UTC, qooban commented
I'm taking over RD-5771, so let me close this one.

2023-04-12 06:43 UTC, closed without merging