RD-5765 Migrate Blueprint Sources widget
cloudify-cosmo/cloudify-stage pull request #2467
Opened 2023-03-06 11:23 UTC by leon-good-life

## Description
Jira ticket: RD-5765

## Screenshots / Videos
N/A

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
`blueprint_sources_spec.ts` 20 March 2023 10:59 IL time- ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4772/pipeline

`blueprint_sources_spec.ts` 15 March 2023 11:39 IL time- ✅ passed:
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4742/

`blueprint_sources_spec.ts` 14 March 2023 16:25 IL time- ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4736/pipeline

`blueprint_sources_spec.ts` 14 March 2023 12:07 IL time:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4733/pipeline

`blueprint_sources_spec.ts` 13 March 2023 - ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4726/pipeline

 

## Documentation
N/A

2023-03-06 12:01 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    }
This shouldn't be necessary - such case is already handled in `widget.tsx`

2023-03-08 18:31 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
>          const paramDeploymentId = params.deployment_id;
i removed it: 
56a3b5a

2023-03-09 11:34 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    }
I removed it: [96a85bc](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/96a85bc500e254d2a13a96c7a21b3b3bb732be0e)

2023-03-10 08:56 UTC, kubama requested changes

2023-03-10 08:56 UTC, kubama commented on .size-limit
> +        "limit": "3.6 MB",
This for sure shouldn't be necessary...

2023-03-10 08:56 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +import { Loading } from 'cloudify-ui-components';
This import is the probable cause of the size increase

2023-03-13 10:47 UTC, leon-good-life commented on .size-limit
> +        "limit": "3.6 MB",
I reverted it

2023-03-13 10:48 UTC, leon-good-life commented
I'm working on fixing check-types right now:

2023-03-14 08:27 UTC, leon-good-life commented on .size-limit
> +        "limit": "11.2 MB",
We don't need to increase, I reverted it now: [db9a13a](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/db9a13af0277901bbdb3abf7814c496bcc258877)

2023-03-14 09:25 UTC, kubama commented on widgets/blueprintSources/src/widget.tsx
> +        const deploymentIdRefined: string = Array.isArray(deploymentId) ? deploymentId[0] : deploymentId ?? '';
I'd rather rename `deploymentId` as it's not an id but rather an id or an array of ids. Then `deploymentIdRefined` could be just `deploymentId`.

2023-03-14 09:25 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +            const blueprintRootDirectory = data.blueprintTree.children![0].key;
Maybe we could align `children` type instead?

2023-03-14 09:49 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
> +    deployment_id: string;
I changed to camelCase: 996a419

2023-03-14 09:55 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +            const blueprintRootDirectory = data.blueprintTree.children![0].key;
[0ba07a5](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/0ba07a5c31871c84b29972d633dad7426a509301)

2023-03-14 09:58 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
> +        const deploymentIdRefined: string = Array.isArray(deploymentId) ? deploymentId[0] : deploymentId ?? '';
deploymentIdRefined --> rawDeploymentId:
[5ab8a97](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/5ab8a978eafddf22abb2561070b3f488c5a66b71)

2023-03-14 10:03 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
> +        if (!data || _.isEmpty(data)) {
[8e0249d](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/8e0249d5ebd6b0d2416fdb738599e634eea6c35d)

2023-03-14 12:53 UTC, kubama commented on widgets/blueprintSources/src/widget.tsx
> +        const rawDeploymentId = toolbox.getContext().getValue('deploymentId');
```suggestion
        const deploymentIds = toolbox.getContext().getValue('deploymentId');
```

2023-03-14 12:53 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +                                            {loop(data.importedBlueprintIds[index], tree.timestamp!, tree.children!)}
As already commented - instead of using `!` it would be good to align types.

2023-03-14 12:53 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    const blueprintTreeChildren: ScanningItem[] = data.blueprintTree.children ?? [];
This additional logic wasn't needed before. Can't we just align types instead of applying workarounds?

2023-03-14 13:01 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
> +        const rawDeploymentId = toolbox.getContext().getValue('deploymentId');
[72402b6](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/72402b62f8af1237516f31fba7f5f7e323cfd460)

2023-03-14 13:34 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +                                            {loop(data.importedBlueprintIds[index], tree.timestamp!, tree.children!)}
I'm not sure I understand what you mean align types. Do you mean to change the `tree.timestamp` to  `tree.timestamp as string`?.

2023-03-14 13:47 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    const blueprintTreeChildren: ScanningItem[] = data.blueprintTree.children ?? [];
I removed those lines: [4e33970](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/4e33970960d490213dd523f8f9145e296a555a45)

2023-03-14 13:47 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +                                            {loop(data.importedBlueprintIds[index], tree.timestamp!, tree.children!)}
I reverted this change: [4e33970](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/4e33970960d490213dd523f8f9145e296a555a45)

2023-03-15 08:40 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    data: Exclude<WidgetData<BlueprintSourcesData>, undefined>;
Wouldn't `NonNullable` fit here?

2023-03-15 08:40 UTC, kubama commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +                                            {loop(data.importedBlueprintIds[index], tree.timestamp!, tree.children!)}
But this doesn't address my comment.

Can't we just align types of `tree.timestamp` and `tree.children` to be non-nullable? It's a question. Looking at the flow I suspect we should be able to assume it's safe to do this.

Alternatively, we could change `loop` signature to accept nullish values, again looking at the code I think it should be possible to do without changing the function logic.

Compared to the two proposed solutions, using `!` operator or aligning argument values are just workarounds for inaccurate typings.

2023-03-15 09:24 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +    data: Exclude<WidgetData<BlueprintSourcesData>, undefined>;
Changed to `NonNullable`: 84a2754

2023-03-15 09:58 UTC, leon-good-life commented on widgets/blueprintSources/src/BlueprintSources.tsx
> +                                            {loop(data.importedBlueprintIds[index], tree.timestamp!, tree.children!)}
I reverted everything and removed the `?` (optional undefined) from where the types are defined: [3960600](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/39606000a5cf36d0ca994018b7138887a61dc688)

2023-03-16 10:55 UTC, kubama commented on backend/handler/SourceHandler.types.ts
> +    children: ScanningItem[];
Looking at the logic, `children` makes sense only when `isDir === true`. Can we use discriminated union here so this was reflected?

2023-03-16 12:07 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
> +    children: ScanningItem[];
[50f40c9](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/50f40c9191abf7517cc64d87a971bd1df8993366)

2023-03-17 08:23 UTC, kubama commented on backend/handler/SourceHandler.types.ts
> +    children: ScanningItem[];
Just use correct type for `item`

2023-03-17 08:26 UTC, kubama commented on backend/handler/SourceHandler.types.ts
> +    children: EmptyArray;
Why at all do we need `children` prop in this case?

2023-03-19 12:37 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
> +    children: EmptyArray;
[d3f3612](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/d3f36122d9e9449b3c554541d39637d4a0930b99)

2023-03-19 12:59 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
> +    children: ScanningItem[];
right, i don't know how i didn't see it

2023-03-19 13:00 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
> +    children: ScanningItem[];
[7df42f2](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/7df42f2fe96f1afbe9f55592bd13c575c4ab40a3)

2023-03-20 08:36 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
> +    title: string;
I removed duplication: [8fc9ec9](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/8fc9ec93f6a00f301be91e210cb859bc8a311e6e)

2023-03-20 09:06 UTC, leon-good-life commented on backend/routes/BlueprintUserData.ts
> +                if (data === null) return res.status(500).send({});
i thought maybe `return res.status(404).send({});`  here.
But the data is null in the following cases:
- symbolic link
- hidden unix path
- not a file and not a directory
-  error accessing the directory

2023-03-20 09:08 UTC, leon-good-life commented on backend/routes/BlueprintUserData.ts
> +                if (data === null) return res.status(500).send({});
I changed my mind here.

2023-03-20 13:51 UTC, kubama commented on backend/test/handlers/SourceHandler.test.ts
> +            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
Wouldn't it be equal but shorter?
Wouldn't it be sufficient?
```suggestion
            expect(archiveTree?.children?.[0].isDir && archiveTree?.children?.[0].children[0].key
            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
```
`archiveTree?.children?.[0]` could be also extracted to a variable

2023-03-20 13:51 UTC, kubama commented on backend/routes/BlueprintUserData.ts
> +                if (data !== null) {
Do we need this if we have another `if` in L34? Or maybe the other one could be dropped now?

2023-03-20 13:51 UTC, kubama commented on backend/routes/SourceBrowser.ts
> +    (req, res: Response<GetSourceBrowseBlueprintArchiveResponse | null>, next) => {
I guess `null` should be part of `GetSourceBrowseBlueprintArchiveResponse`

2023-03-20 13:51 UTC, kubama commented on widgets/blueprintSources/src/widget.tsx
> +                },
Can we change the type of `blueprintTree` to allow nullish value instead of creating this artificial object?

2023-03-21 09:52 UTC, leon-good-life commented on backend/handler/SourceHandler.types.ts
>      isDir: boolean;
I removed it: [7350696](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/7350696bfa508f1f9ed8bd8fd2ee9fa3564b6944)

2023-03-21 09:59 UTC, leon-good-life commented on backend/handler/SourceHandler.ts
> +        } as ScanningFile;
[a0cd68c](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/a0cd68c2d9d84101942594dc0f16da031df31991)

2023-03-21 09:59 UTC, leon-good-life commented on backend/handler/SourceHandler.ts
> +                    ...(archive as ScanningDir),
[a0cd68c](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/a0cd68c2d9d84101942594dc0f16da031df31991)

2023-03-21 10:14 UTC, leon-good-life commented on backend/test/handlers/SourceHandler.test.ts
> +            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
I made it shorter:
[9c56437](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/9c5643751387b22b55519abb4159e9a408def41c)

extracting to a variable didn't work:
<img width="813" alt="Screenshot 2023-03-21 at 12 12 10" src="https://user-images.githubusercontent.com/17104212/226576174-6d959041-4fe8-499c-ac5e-18f0a9af5c49.png">

2023-03-21 10:16 UTC, leon-good-life commented on backend/test/handlers/SourceHandler.test.ts
> +            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
it can be changed to:
```typescript
const tree = archiveTree && archiveTree?.children?.[0];
expect(tree && tree.isDir && tree?.children?.[0].key).toEqual('subdir/fileNameSpecial%3F%23Characters');
```

2023-03-21 10:20 UTC, leon-good-life commented on backend/routes/BlueprintUserData.ts
> +                if (data !== null) {
I removed the `if` in L34: [5a0eec9](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/5a0eec90af82cd467aa1aa3b4fd25940e02fb8b3)

2023-03-21 11:22 UTC, leon-good-life commented on widgets/blueprintSources/src/widget.tsx
> +                },
it causing the following error:
<img width="1372" alt="Screenshot 2023-03-21 at 13 21 24" src="https://user-images.githubusercontent.com/17104212/226591663-f476e46f-e14c-4090-8e1b-1520322118d5.png">

2023-03-21 12:25 UTC, kubama commented on backend/test/handlers/SourceHandler.test.ts
> +            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
Since we are using `?.` this should work equally well I think:
```
const tree = archiveTree?.children?.[0];
```
and then we can use `?.` again for the first `tree` condition but drop it for the second one (I didn't validated it though):
```
expect(tree?.isDir && tree.children[0].key).toEqual('subdir/fileNameSpecial%3F%23Characters');
```

2023-03-21 12:47 UTC, leon-good-life commented on backend/test/handlers/SourceHandler.test.ts
> +            ).toEqual('subdir/fileNameSpecial%3F%23Characters');
I changed it: [352969e](https://github.com/cloudify-cosmo/cloudify-stage/pull/2467/commits/352969e5aabd0a4a76d0826cac078cb7782c1d40)

2023-03-21 13:15 UTC, kubama commented on backend/test/handlers/SourceHandler.test.ts
> +            const tree = archiveTree && archiveTree?.children?.[0];
```suggestion
            const tree = archiveTree?.children?.[0];
```

2023-03-21 14:12 UTC, kubama approved these changes

2023-03-21 14:19 UTC, merged